### ISSUE TITLE
hide vertical scrollbar

### ISSUE THREAD

**Issue by b1n3t8ks** [inuyaksa/jquery.nicescroll#153]
Hi,

is there a paramenter like:

horizrailenabled:false/true

just for the vertical scroll bar? I can not find anything about this issue - i only want the horizontal scrollbar.

thx

**Comment by rijosh** [comment]
We can fix it through CSS

.nicescroll-rails.nicescroll-rails-vr {
    opacity: 0 !important;
    display:none;
}
