### ISSUE TITLE
.getNiceScroll().show().resize() bounce problem and delayed show

### ISSUE THREAD

**Issue by glhfu2** [inuyaksa/jquery.nicescroll#174]
Hi,

i'm using niceScroll with jquery ui dialogs.

I'm currently hiding the scrollbars on dragstart, and showing them on drag stop, like this:

``` javascript
            .bind("dialogdragstart", function () {

                $widget.find('.nicescroll').getNiceScroll().hide();

            })
            .bind("dialogdragstop", function () {

                $widget.find('.nicescroll').getNiceScroll().show().resize();

            })
```

This is working, but the .show().resize() parts generate a little graphical bug: the show() is immediately executed, but the resize() is delayed because of this:

``` javascript
      self.delayed('resize', self.onResize, 30); return self;
```

So the effect is:
- the bar is immediately shown, but not yet updated and at an old position, because the resize() event has not fired yet
- after 30ms, the resize() event is fired, and the bar size and position got updated.

I solved this problem delaying the show also by 40ms, like the resize() event:

``` javascript
        var _show = that.show;

        that.show = function () {
            that.delayed('show', _show, 40); return that;
        } // event debounce
```

I think that having a delayed .show() is useful and i cannot find side effects; should we always implement this delayed show?

**Comment by estevaosa** [comment]
Hello guys, the last version 3.6.6 of NiceScroll() still have problem with resize function.. do you know smething? RangeError: Maximum call stack size exceeded.
