### ISSUE TITLE
"touchbehavior: true" and Scrollbar dragging

### ISSUE THREAD

**Issue by Seuthes** [inuyaksa/jquery.nicescroll#177]
If touchbehavioris enabled, i cannot use scrollbar to scroll. It works fine if i disable touchbehavior. But otherwise the scrollbar is registered as a part of div, which you scroll by dragging.

Is it possible to make the scrollbar also work normally "undertouchbehavior: true"?

**Comment by AndreyCursin** [comment]
It does not work on the touch screen in the Firefox 48.0
and tap on the links does not work in Chrome 50.0
