### ISSUE TITLE
IE8 cannot auto hide the scrollbar when the page load in version > 3.18 

### ISSUE THREAD

**Issue by alanlo** [inuyaksa/jquery.nicescroll#183]
Hello,

Some of the issues fixed in 3.18 is worked for my code. However, in > 3.18, the scrollbar will be displayed in IE8 even I set to autohidemode to true.

Is it possible to fix this issue?

Thanks.

**Comment by gpashis** [comment]
This issue is resolved but in IE8 when I am trying to force hide programmatically using the function, its is not working. 
<pre>
// 6. Hide scrollbars:
$("#mydiv").getNiceScroll().hide();
</pre>

In IE8 getNiceScroll() gives undefined.
