### ISSUE TITLE
Memory Leaks after removing nicescroll

### ISSUE THREAD

**Issue by mjeanroy** [inuyaksa/jquery.nicescroll#194]
I used the plugin in my application and I detected some memory leaks.
You can check by doing the following steps :
- Take a heap snapshot from Chrome Dev Tools.
- Initialize nicescroll plugin on a div element.
- Call the remove method of nicescroll plugin and remove div element from the DOM.
- Take a heap snapshot from Chrome Dev Tools.

At this step, I expect that the new snaphsot should be pretty similar than the first but I can see many "Detached Dom entry" (corresponding to the div element I previously removed).

I tested several time and each time, same results.

I added following lines at the end of remove function :

```
     for (var i in self) {
         if ((self[i] !== undefined) && (self[i] !== null)) {
             // Set to undefined because prototype fields cannot be deleted
             self[i] = undefined;
             delete self[i];
         }
     }
```

It deletes everything but I am not sure this is the the best way to fix this (maybe there are some timers or anything else we should clear or remove properly).

With these lines, I don't see anymore any Detached Dom Entry.

I can try to spend more time on it and send you a pull request if I can find precisely where is the leak or to find a better solution.

**Comment by jayesh-sapkale** [comment]
thank you @inuyaksa and thank you all contributors of niceScroll.+3.5.0
solve the leak problem..
it release the memory after scroll removed.
