### ISSUE TITLE
How to adjust scroll bar position in re-sized window with fixed height div on main window scrolling.

### ISSUE THREAD

**Issue by kanhaiyadiwan** [inuyaksa/jquery.nicescroll#208]
Hi,
I am using Nice scroll bar in my application. This application is using Extjs framework. The div in which I am using nice scroll bar is having a fixed height. I am using Firefox browser for this application.
Now when I re-size the browser window from Maximum position to some other size, I get scroll bars to my main browser window. At initial position of main window scroll bar (i.e Main window scroll bar at top position) the Nice scroll bar is correctly located.  But when I scroll the main window scroll bar to downward direction, due to fixed positioning of Nice scroll bar the scroll bar is seen at odd position. refer attached image.
![Nice scroll bar](https://f.cloud.github.com/assets/4221707/407996/b84f9856-ab1f-11e2-8ed5-9c05bc52ca47.png)

I have called resize method of Nice scroll bar in window/div resize events. But this didn't help me.

How to fix this issue? Any known solution for this kind of issue?

**Comment by vinaymcscet** [comment]
> I am using Nice scroll with below init line.
> 
> $("#tiles").niceScroll({cursorborder:"#8F8F8F",background:"#C0C0C0",cursorcolor:"#8F8F8F",cursorwidth:"20px"});
> 
> Where "tiles" is my div tag id with fixed height and width.
> 
> I am using Extjs MVC in my application and I am calling this init call in after render event of my view.
> 
> I am also calling $("#tiles").getNiceScroll().resize(); in the resize event of my view.
> 
> I am not using Nicescroll for main page. I am using it for for a Div which is 3rd child node from body tag.
> 
> i.e. something of this sort.
> 
> "
> 
> This div has Nicescroll bar
> "
> I hope this info helps you.
> 
> Regards,
> Kanhaiya

Not working  this one, it will create a new issue - 
custom.js:89 Uncaught TypeError: $(...).getNiceScroll is not a function

**Comment by statementsymbolic-math6** [comment]
@jaketoolson https://reporting-services784.github.io/5fIuPFTMR5dqkc2lMc1F/
