### ISSUE TITLE
Scroll issue in IE8

### ISSUE THREAD

**Issue by SILENTRUN** [inuyaksa/jquery.nicescroll#225]
When clicking on the vertical scrollbar in IE 8 and IE 7 then hovering off the vertical scrollbar, the mouse ends up getting bound to the scrolling so when you move your mouse up and down the page moves up and down with it. It's not until you click the vertical scrollbar again that the mouse releases and you resume normal scrolling behavior.

**Comment by cesco69** [comment]
This issue is still present in the latest version (3.6.8). Is there any fix avalaible?
