### ISSUE TITLE
Table scroll

### ISSUE THREAD

**Issue by ronlobo** [inuyaksa/jquery.nicescroll#238]
Hey everyone,

is it possible to use nicescroll within a table with fixed header to make the tbody element scroll?

Thanks in advance

Greets

**Comment by nil135** [comment]
Also You can use div inside tbody of table and apply scrollbar on that div("scrollfix").
for e.g.,
<table>
           <thead>
                        <tr>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th></th>
                        <tr>
           <thead>
          <tbody>
                       <tr>
                             <td colspan="4">
                                        <div class="scrollfix">
                                                 <table>
                                                            <tbody>
                                                                        <tr>
                                                                             <td></td>
                                                                             <td></td>
                                                                             <td></td>
                                                                             <td></td>
                                                                        </tr>
                                                            </tbody>
                                                 </table>
                                        </div>
                             </td>
                       </tr>
          </tbody>
</table>

I hope it can help you. I have applied this trick.
