### ISSUE TITLE
jQuery UI Dialog - nicescroll disappears on 2nd open

### ISSUE THREAD

**Issue by jasonday** [inuyaksa/jquery.nicescroll#254]
I'm using nicescroll with jQuery UI Dialog. Namely, I'm attaching nicescroll on all dialogopen events to the content, .ui-dialog-content. 

We use ui dialog as a "quickview" for products - each click of a product opens a dialog and the contents are loaded dynamically into the content of the dialog. The dialog stays the same on the page, it's just opened/closed and new content injected on open. 

Nicescroll won't show when the dialog is opened for the second time, although the element receiving the nicescroll is the same (ui-dialog-content). The nicescroll rails are still in the DOM, however they are no longer visible. I've tried using the resize method when the new content is injected into the dialog, but that has no effect.

I also attempted to $.remove the object on dialog close and reinitate on dialog open, however that did not work either.

Thoughts?

**Comment by CallumH2410** [comment]
Why is this closed without an answer, I have this problem too. Is there a solution?
