### ISSUE TITLE
 delaylist null error on hidding element

### ISSUE THREAD

**Issue by PlippiePlop** [inuyaksa/jquery.nicescroll#260]
When you hide  (display:none) the container which has a nicescroll attached to it. It causes the nicescroll generate a delaylist of null error.

After close inspection it is in the this.delayed function on line 358 because of the setTimeout it thinks the 'self' is still there but in fact it's null because of the disappearance of the container. To prevent this error I changed the code to:

 tt:setTimeout(function(){
                     if(self!==null){
                         self.delaylist[name].tt=0;
                         fn.call();
                     }
                    },tm);

This fixes the issue.

**Comment by tcsehv** [comment]
The issue is still not fixed in the code

**Comment by PlippiePlop** [comment]
Still there in 3.6.0

**Comment by hastom** [comment]
still not fixed in 3.6.0 confirmed

**Comment by inuyaksa** [comment]
Fixed soon, realy.

**Comment by inuyaksa** [comment]
@sid6581 great idea, I hope to working on soon.
