### ISSUE TITLE
Can't interrupt current scroll until rail's stopped moving

### ISSUE THREAD

**Issue by Alhadis** [inuyaksa/jquery.nicescroll#316]
Just something that's bugging me (and possibly other users used to skimming large bodies of content very quickly)...

When scrolling in one direction down the page, attempting to scroll back up again isn't gonna work until the rail's finished moving. This isn't a huge issue, but one that'd be damn nice to see fixed.

For instance, try scrolling your mousewheel downwards and quickly trying to scroll back up again. You'll notice the rail won't respond instantly.

**Comment by MikeRich88** [comment]
I agree with this. This script is terrible.

I blocked it on all sites using Adblock and this filter:
jquery.nicescroll*.js
