### ISSUE TITLE
Operlapping scrolbars in Bootstrap tabs

### ISSUE THREAD

**Issue by 7onmoy** [inuyaksa/jquery.nicescroll#319]
If we initialize nicescroll on multiple tabs (Bootstrap), the scroller from non-active tabs are also visible at all times.

This fiddle is a recreation of the issue: http://jsfiddle.net/LittleLebowski/B86me/15/

**Comment by Arvn41** [comment]
hello , 
I have tried elvismdev's code and its work like charm, same code am trying to modify but scrollbar still overlap.

In my structure there is panel under tab pane, and table responsive div under panel, i want to apply scrollbar to table-responsive class

my html is 
<div id="trades" class="tab-pane fade">
                    <div class="panel panel-default">
                        <div class="panel-heading">                           
                        </div>
                        <div class="table-responsive" id="div_TradeOrder">
                            <table class="table tab-table" id="tbl_TradeOrder"></table>
                        </div>
same structure for each tab with different table ID
my js code is 

 $('body').on('click', '[data-toggle="tab"]', function () {
        $(".tab-pane .panel .table-responsive").getNiceScroll().hide();
        $($(this).attr('href')).find(".tab-pane .panel .table-responsive").niceScroll({
            cursorcolor: "#2f6098",
            cursorwidth: 10,
            cursoropacitymin: 0.7,
            autohidemode:"false"
        });        
        $($(this).attr('href')).find(".tab-pane .panel .table-responsive").getNiceScroll().show();
     })

for first tab its working but for others its not working properly, when i inspect all scrolls are created by plugin but not showing proper tab scroll, if I resize window after tab click its work like charm.

Please help me where am going wrong
