### ISSUE TITLE
Not scrolling on lastest Firefox with HTML5 inside iframe

### ISSUE THREAD

**Issue by numediaweb** [inuyaksa/jquery.nicescroll#322]
I spent a lot of time trying to debug this!
If you use jquery.nicescroll on an iframe that loads an HTML5 file;

```
<!DOCTYPE html>
<html lang="en">
  <head>...
```

It doesn't scroll at all in Firefox but scrolls on chrome and other moder browsers (latest versions). 

Changing the document type to;

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="en">
  <head>...
```

Works.. Is is a Firefox bug?

**Comment by justgeek** [comment]
check this post out : https://code.google.com/p/jquery-nicescroll/issues/detail?id=23

**Comment by Jeeosch** [comment]
Hi justgeek!

That's kind of complicated I feel ... also, there is no feedback, whether that works or not.
It would be better, I think, if the developer would properly address the issue, since otherwise this is a great plugin!

**Comment by Jeeosch** [comment]
Just to reconfirm:
I installed the latest version (3.6.0) and still observe the same issue. I hope that this will be solved soon.
Many thanks in advance to the developer!!

**Comment by brunowego** [comment]
+1

**Comment by shmdhussain** [comment]
I am also observing the same issue with 3.6.0. Please post once it is resolved. I think If we remove the overflow:hidden in the <html> tag , issue seems resolved but the purpose of using the framework lost

**Comment by Jeeosch** [comment]
This issue is still there, I'm afraid ... :-(
I have just uploaded version 3.7.0 to my site and it still doesn't scroll when hovering over an iFrame.
Please kindly fix this nasty issue.
Many thanks in advance!!

**Comment by inuyaksa** [comment]
Sorry, I closed very old issues without feedback.

Can you send me a link to test your issue?

**Comment by Jeeosch** [comment]
Sure! Here it is: http://www.thursday-evening-band.de/blog

Please use that little British flag in the little menu on the left to switch to English (not important for the issue, in fact).

As mentioned I have installed the latest version, which is 3.7.0 I understand.

**Comment by inuyaksa** [comment]
Thanks, I'm investigating.

**Comment by inuyaksa** [comment]
I found this issue it's by design.
I mean, major browsers don't bubble iframe mouse wheel events to page, only scroll events.
This doc explains: https://stackoverflow.com/questions/14065677/retrigger-mousewheel-events-from-iframe
A solution is write code into iframe to retrigger mouse wheel event to page.

**Comment by Jeeosch** [comment]
I do not seem to get it to work, I'm afraid.

I tried putting the code into the head section of the page called via the iFrame, which didn't work.
Including the code in the head section of the parent page is disabling nicescroll.

The name of my iFrame is "blogFrame".

How exactly do I need to include the code snippet given by the link above, i.e. _this.bind(jQuery(document.getElementById("#blogFrame").contentDocument),"mousewhee‌l",this.onmousewheel);_?

**Comment by inuyaksa** [comment]
I'm trying a trick. I'll write soon.

**Comment by Jeeosch** [comment]
Looking forward ... :-)

**Comment by inuyaksa** [comment]
Please try this,
It's a snippet helper to load into iframe page. 
It retrigger mouse wheel event to parent page.
[jquery.nicescroll.iframehelper.js.zip](https://github.com/inuyaksa/jquery.nicescroll/files/1066340/jquery.nicescroll.iframehelper.js.zip)

**Comment by Jeeosch** [comment]
Hi!

Many thanks for all the efforts, but it still doesn't work, I'm afraid.
I've included the snippet in both the iFrame source page as well as the parent page, without success.

Any other ideas?

**Comment by inuyaksa** [comment]
I don't find script into your page:
http://www.thursday-evening-band.de/Blog_DE/index.php
You have to load helper script into this page (and other ones loaded by iframe).

**Comment by Jeeosch** [comment]
I have tried the helper script, but since it didn't work, I have removed it again.
I will install it again and will let you know.

**Comment by Jeeosch** [comment]
OK ... done!

I've loaded the js file you provided into the head section of the pages
[http://www.thursday-evening-band.de/Blog_DE/index.php](http://www.thursday-evening-band.de/Blog_DE/index.php),
[http://www.thursday-evening-band.de/Blog_EN/index.php](http://www.thursday-evening-band.de/Blog_EN/index.php)
and
[http://www.thursday-evening-band.de/blog/index.php](http://www.thursday-evening-band.de/blog/index.php), which is the parent page.

The child pages above are not meant to be called directly since they deliver the content of the iFrame on the parent page.

It still doesn't work, I'm afraid.

**Comment by inuyaksa** [comment]
Sorry, I write you 2 steps to resolve your issue.
Only in the child pages, in parent page is not needed.
Load script at the end of your page, before ending body tag.

**Comment by Jeeosch** [comment]
Works!
Many thanks!!

**Comment by gomarion** [comment]
Hello inuyaksa,

I see that you have found a solution for this with iFrames that you have control over in your own server. Is there any chance for external iFrames like YouTube or Vimeo?

Thanks!

**Comment by inuyaksa** [comment]
Hi @gomarion try iframehelper script
It's a first tentative to resolve scrolling issue with xdomains iframe.
