### ISSUE TITLE
Add semantic version tags for plugin releases to allow better Bower support

### ISSUE THREAD

**Issue by FlyingDR** [inuyaksa/jquery.nicescroll#326]
This plugin is registered as a [Bower](http://bower.io/) component (as can be seen [here](http://sindresorhus.com/bower-components/#!/search/jquery-nicescroll)), but currently Bower can't operate with plugin's versions:

```
>bower info jquery-nicescroll
bower not-cached    git://github.com/inuyaksa/jquery.nicescroll.git#*
bower resolve       git://github.com/inuyaksa/jquery.nicescroll.git#*
bower checkout      jquery-nicescroll#master
bower resolved      git://github.com/inuyaksa/jquery.nicescroll.git#62ef3c51f6

{
  name: 'jquery-nicescroll',
  homepage: 'https://github.com/inuyaksa/jquery.nicescroll'
}

No versions available.
```

Problem is that this repository doesn't satisfy Bower [requirement](http://bower.io/#registering-packages) for using [semantic version](http://semver.org/) tags for marking releases.

Adding release tags is [very easy](https://github.com/inuyaksa/jquery.nicescroll/releases/new) at GitHub and it will highly improve use of your great plugin through Bower.

**Comment by IvoPereira** [comment]
+1
