### ISSUE TITLE
Horizontal Scrollbar only

### ISSUE THREAD

**Issue by ronlobo** [inuyaksa/jquery.nicescroll#332]
Good morning,

it's possible to add an option for the vertical srcollbar that might disable it?
Like for the horizontal scrollbar we have the option to set it with "horizrailenabled", it be would be nice to do the same for the vertical scrollbar with "verticalrailenabled".

Thanks for adding it to the features list :)

Greetz

**Comment by elitzer2** [comment]
I also would like the ability to have a horizontal scroll only. Has there been any progress on this?
