### ISSUE TITLE
How to use Nicescroll plugin for right-to-left direction?

### ISSUE THREAD

**Issue by Ar-Gorgin** [inuyaksa/jquery.nicescroll#333]
I use Nicescroll plugin for change style of div scroll bar .
It is ok for ltr direction, but when i uset it in direction:rtl of Page, don't work mousewheel.

I use rtlmode:true, railalign:"left" options but don't work.

Can i use this plugin for RTL pages?

**Comment by ramadanko** [comment]
This is my code for a project 
(function () {

    var rtl_direction = $('body').attr('dir');

    var footer = $('.footer-news');
    var footer_scroll = footer.niceScroll(
        {
            cursorcolor: "#0085c9",
            cursorwidth: "12px",
            cursoropacitymin: 1,
            cursorborder: 'none',

        }
    );
    footer_scroll.cursor.parent().css({
        'background-color': '#b4c2ce',
        'border-radius': '5px',
        'padding': '1px 0px'
    });

    setTimeout(function () {
        if( rtl_direction){
            footer_scroll.cursor.parent().css({
                'left':footer.offset().left
            });
        }
    }, 1000);
}());// nice scroll closure

i'm setting the timeout for waiting the plugin to add it configuration
