### ISSUE TITLE
Nicescroll keeps scrolling when i move mouse cursor to top/bottom of the page, without scrolling

### ISSUE THREAD

**Issue by neara** [inuyaksa/jquery.nicescroll#360]
Happens on mac maveric, chrome and safari. When i move mouse cursor to top/bottom of the page, not scrolling, just moving the mouse down (to devtolls or such), activates scrolling. 
Small thingie, but drives me nuts! lol

**Comment by IvoPereira** [comment]
+1. Happens here too on OSX Chrome too.

v.3.5.4

Please tag release 3.6, so we could update it on Bower.
