### ISSUE TITLE
Mouse wheel not working on ie9

### ISSUE THREAD

**Issue by the-iceman** [inuyaksa/jquery.nicescroll#366]
Hi.Great plugin but i see that on ie9 ( i didn't tested on any other ie versions ) the mouse wheel is not working.You can scroll only if you drag the scroll bar with your mouse .I saw that this bug is present on previous versions too. I use windows7 .Anyone else have this issue ?

**Comment by lucasazevedoqx** [comment]
I have the same problem :(
