### ISSUE TITLE
Padding and width rail

### ISSUE THREAD

**Issue by bitxl** [inuyaksa/jquery.nicescroll#373]
I call nicescroll with the following options:

```
$(".js-nicescroll").niceScroll({
        cursorwidth: 13,
        cursorborderradius:3,
        cursorborder: "1px solid #cccccc",
        cursorcolor: "#d7d7d7",
        autohidemode: false,
        background: "#ebebeb",
        railpadding: {top: 2, left: 2, bottom: 2, right: 2}
    });
```

However, the calculated cursor width is 13px, including the border that would be 15px.
The calculated width of the rail is 19px, which is fine as it takes into account the padding but as the box-sizing is not set to border-box the total width of the rail becomes 23px and the left alignment is incorrect! :(
So either box-sizing: border-box needs to be added to the rail or the width needs to be the cursorwidth + cursorborderwidth \* 2 and the calculation of the left offset needs to be done also taking the padding into account.

**Comment by librisius** [comment]
I found the same problem. But for me railpadding: left - totally doesn't work

**Comment by t-yng** [comment]
I met same problem.
rails width is not correct, when I set railpadding: left and right.

**Comment by ali-xharif** [comment]
Applying min-width to .nicescroll-rails along with left, top, right, bottom solved the problem of width.
