### ISSUE TITLE
Mousewheel button "click scroll" not working

### ISSUE THREAD

**Issue by gstaruk** [inuyaksa/jquery.nicescroll#377]
When you press the mousewheel button (middle click) and move mouse up or down, it scrolls the document body instead of the DIV.

This can be replicated on the official demo page: http://areaaperta.com/nicescroll/demo.html

Since all other scrolling events are relative to the DIV in which the cursor is present, therefore the DIV which has been middle clicked in should be the one that gets scrolled.

Tested in Firefox 28 and Chrome 33

**Comment by sinni800** [comment]
And it's been there since 2014? This is abysmal, to be honest.

**Comment by markinfurkin** [comment]
please! fix this!

**Comment by Starofall** [comment]
+1
