### ISSUE TITLE
Enable only if needed

### ISSUE THREAD

**Issue by yukulele** [inuyaksa/jquery.nicescroll#378]
some os or browsers no really need niceScroll (ios, os x lion+, android, ...),  
i suggest to add an option to apply it only if native scrolbar have width.

**Comment by rspenc29** [comment]
More than 2 years later and this is still pissing me off. This plugin ruins websites on mac.

**Comment by yukulele** [comment]
Why have you close this issue?

**Comment by inuyaksa** [comment]
Hi there, I'm closing very old issues for a more clean situation.
About your suggestion, I think It's a website programmer decision on which browser/os use nicescroll.

**Comment by rspenc29** [comment]
Use a macbook for about a week then see how your plugin performs once you are used to the native trackpad. Not only does the scrolling completely suck but the 2 finger swipe to navigate back in the browser history is hijacked and broken too.

**Comment by inuyaksa** [comment]
I'm investigating soon, sorry I don't have a mac.
Then my reply is not about your problems but the question on "no really need".
So if you have an issue, please open a new issue, It's useful some link of websites with such a problem.

**Comment by rspenc29** [comment]
I think they are related. If your plugin doesn't work as good as native scrolling on some devices then not only is it not needed, it's broken, especially if it breaks all native gestures.

Here is an example I just came across. There are many others but I don't remember them since i don't stick around.

https://www.omnicoreagency.com/

plugin is in https://www.omnicoreagency.com/wp-content/themes/betheme/js/plugins.js

**Comment by inuyaksa** [comment]
Sorry don't found a mac to try swiping.
So I try to resolve gesture problems.
I update script on my site, please give a look and let me know if swipe works.
(beware of browser cache)
https://nicescroll.areaaperta.com/

**Comment by inuyaksa** [comment]
I've tested on a mac with magic mouse, swipe back gesture works on last dev version 3.7.2.
You can try here: https://nicescroll.areaaperta.com/
I'm waiting for your feedback

**Comment by rspenc29** [comment]
Thank you. While I wish this was disabled completely on mac, this is a good start. I appreciate you taking the time to fix it.

**Comment by LeeSwagger** [comment]
This fix breaks diagonal swipe on macbook trackpad
![screenshot_mac](https://user-images.githubusercontent.com/11897191/52042810-1ff05900-254f-11e9-9e6a-5174bcc60dfe.png)
