### ISSUE TITLE
Scrollbar displayed but not scrollable on IE11 with Windows 8 touch device

### ISSUE THREAD

**Issue by robertfausk** [inuyaksa/jquery.nicescroll#407]
On touch/scroll the nicescrollbar is shown with correct height but the scrolling does not happen.

**Comment by kissmd** [comment]
Hi
our project still can reproduce the missing scrollbar on win8 + ie11 with 3.6.0 (Nov 21, 2014).

What kind of evidences shall i provide to get this fixed soon?

Thank you
misu

**Comment by codingyourlife** [comment]
I can confirm that my surface RT with all updates can't scroll with touch when this plugin is enabled

**Comment by codingyourlife** [comment]
I can confirm that scrolling on Surface RT with IE works now. Worked as soon as I updated, thanks!
