### ISSUE TITLE
Disable horizontal scroll using mousewheel, when no vertical scroll

### ISSUE THREAD

**Issue by gbdlin** [inuyaksa/jquery.nicescroll#415]
By default, when there is no vertical scroll, but there is horizontal one, mouse wheel will cause scrolling left and right instead of up and down.

Is there any possibility to disable this behaviour, but don't disable horizontal scroll (so I can still scroll horizontal, but by using for example horizontal mouse whell, swipe gesture, drag&drop etc)?

**Comment by itonic-minrai** [comment]
Set oneaxismousemode option value to false

`oneaxismousemode: false,`

`$(selector) .niceScroll({ oneaxismousemode: false})`
