### ISSUE TITLE
IE 11

### ISSUE THREAD

**Issue by falkesgaard** [inuyaksa/jquery.nicescroll#418]
Doesn’t work on Windows Phone (IE11 mobile) or in IE11 in touch-mode.
Any thoughts ?

**Comment by ArtbyArjan** [comment]
According to [this release note](https://github.com/inuyaksa/jquery.nicescroll/commit/af737e0f2f6d0f22c66f65809b0c93e396216e51), touch support for IE11 should work, but testing this in IE11 on a Windows Surface with Windows RT 8.1, I can't even scroll the [demo page](http://nicescroll.areaaperta.com/demo.html).
The window and elements only scroll when touching the scrollbar track.

**Comment by astehlik** [comment]
We also have problems with IE Mobile (IE10 on Windows 8 and IE11 on Windows 8.1).

We are using niceScroll for a container in the mobile navigation (only for horizontal Scrolling). Have a look [here](http://www.uni-flensburg.de/portal-studium-und-lehre/studiengaenge/bachelor/?isMobile=1) for a demo.

On windows mobile it is not possible to scroll up and down any more when you are above the niceScroll container. It seems like a problem with the *nativeparentscrolling* feature to me.

We will disable niceScroll for those devices for now as a workaround. Still it would be cool if this gets fixed :)

**Comment by ArtbyArjan** [comment]
Seems to me, support for this plugin is non-excistent since there hasn't been a reply since January this year and the last update was in November 2014

**Comment by inuyaksa** [comment]
Related to #555 ?
