### ISSUE TITLE
CTRL-F not working do nicescroll

### ISSUE THREAD

**Issue by blade1989** [inuyaksa/jquery.nicescroll#419]
When i CTR-F on a page with nicescroll, it doesn't go down, it highlights the words, but doesn't browse to it. I have to manually browse down, to see if they are found. 

Tested on:
- Mozilla Firefox 31.0
- Chromium 36.0.1985

OS:
- Ubuntu 14.04

**Comment by magourneen** [comment]
Hi, I would like to follow-up on this issue. Hoping for the _Ctrl+F _to work in Wordpress in Chrome soon.. Thanks a lot! If it works already, please kindly reply

**Comment by kumareswarank** [comment]
@inuyaksa : Just curious! whenever "wheelprevented " is checked we have "event" with us. Won't it be enough to check "event.ctrlKey" instead of setting it to a variable and resetting it. This removes unnecessary event binding for keydown, keyup, blur, etc. Correct me if i'm wrong.

**Comment by Sasha-Sa** [comment]
hi! still no solution about browsing found words?
