### ISSUE TITLE
nicescroll not working with fancybox

### ISSUE THREAD

**Issue by devland** [inuyaksa/jquery.nicescroll#423]
```
<div class="bottom">
<a class="fancybox" href="imageURL" data-fancybox-group="gallery">
    <img class="image" src="imageURL" />
</a>
</div>

$(".bottom").niceScroll({
    background: "#406D93",
    cursorcolor: "#243D52",
    autohidemode: false,
    speed: 500,
    cursorwidth: "10px",
    cursorborder: "0px solid red",
    boxzoom: false,
    railpadding: {top: '25px', right: 0, left: 0, bottom: '25px'}
});
```

The nicescroll rail gets positioned way down at the bottom of the page.
If I remove the fancybox stuff it works again.

fancybox version: 2.1.5 (Fri, 14 Jun 2013)
nicescroll version 3.5.4

Sidenote:
It really seems a bad idea to add the rail to the body and have it absolutely positioned based on js computations.
Wouldn't have been better to just add it after the content that is being scrolled? So that no absolute positioning would be required?

**Comment by namaljayathunga** [comment]
[There has some trixs.](http://stackoverflow.com/questions/2268330/jquery-fancybox-but-i-dont-want-scrollbars)
