### ISSUE TITLE
Horizantal Scrolling in RTL (Right to Left)

### ISSUE THREAD

**Issue by mahdiit** [inuyaksa/jquery.nicescroll#428]
i have problem in RTL direction in horizontal scrolling
## example:

< div dir="rtl" id="toBeNice" style="width: 200px; height: 200px;" >
< p style="width:1000px;" >< /p >
< /div >

**Comment by ramadanko** [comment]
check this
https://github.com/inuyaksa/jquery.nicescroll/issues/333
