### ISSUE TITLE
scroll wheel not working on chrome

### ISSUE THREAD

**Issue by crerem** [inuyaksa/jquery.nicescroll#429]
Hello,
I have this implementation for nicescroll 
jQuery(document).ready(function ($) {
    "use strict";

$("html").niceScroll({cursorborder:"none" ,cursorcolor:"#393F48",cursorwidth :"12px",background:"#D5D5D5",autohidemode:"true"});  
}

The scrol is rendered ok but in Chrome (v37.0) the scroll wheel is not working. In firefox or opera everything works as expected. Also i have no js errors in console.

What is strange is that everything worked fine until 2 days ago. The code is in a wordpress theme and maybe the 4.0 update had something to do with it.

Any ideea?  
Thanks

**Comment by raselmahmud** [comment]
select body instead of html tag.working fine for me.
$("body").niceScroll();

**Comment by w33zy** [comment]
On the home page for the plugin at http://areaaperta.com/nicescroll/ if you do a Ctrl+F search for a word not on the page, you'll hear the "ding" sound from Chrome. Then, if you try to scroll using a mouse-wheel, nothing happens. 

This is with Chrome 42, IE11, FF36

If I try @raselmahmud suggestion and repeat the steps above niceScroll stops but the normal browser scrolling takes over

**Comment by pawanrajput007** [comment]
Its Working Fine For me
$(document).ready(function () {
    $('body').bind('mousewheel', function () {
        $("body").niceScroll({ autohidemode: false, zindex: 999 }).resize();        
    });    
});

**Comment by FrancisKF** [comment]
Hello,
I had the same problem when the scroll cursor is on vidéeos of iframes on a wordpress theme with jquery.nicescroll.js plugin, which is very annoying in responsive mode.
I solved the problem by adding in the header.php theme:

$ ("body") find ( "iframe") css ({ "pointer-events": "none"});..

Cancels the event pointer to all iframes on the page and it works !
