### ISSUE TITLE
niceScroll 3.5.6 not working in iframes

### ISSUE THREAD

**Issue by IvoPereira** [inuyaksa/jquery.nicescroll#448]
Hello,

I am being able to reproduce this locally and I can confirm that niceScroll is not producing effect on iframes like you can see here: http://jsfiddle.net/u6dfar7j/

Any suggestions?

I've seen that the demo in plugin website is neither available.

**Comment by brunowego** [comment]
+1

**Comment by randNaN** [comment]
+1

**Comment by mishraarvind100** [comment]
niceScroll is not working on iframe of the internal page also. Here I'm attaching the link for you to see.

[https://codepen.io/mishraarvind100/pen/oNvMLYE](url)
