### ISSUE TITLE
Disable scrolling on Modal

### ISSUE THREAD

**Issue by MiPnamic** [inuyaksa/jquery.nicescroll#449]
Hi, I had an issue with NiceScroll and the Modal used in Bootstrap 3.

When the modal is open the user can still scroll the page in the background, actually I trigger the methods Hide and Show once the modal open up or close down for fix this.

Is this just a bad implementation by my side or not?

**Comment by Inggo-inHomePortal** [comment]
Hello. 3.6.0 has fixed the background issue assuming the window does not resize. 

When the window resizes (such as on an iPad, when Hello. 3.6.0 has fixed the background issue assuming the window does not resize. When the window resizes (such as on an iPad, when the user scrolls down and the address bar shortens), the background is scrollable once again.

**Comment by luchorengo** [comment]
Is there a way to fix this for fancybox 2? When modal opens the user can still scroll the page in the background as in bootstrap.

**Comment by PaykomanVll** [comment]
Hmm im interessted too to fix it on fancybox...
If fancybox open the page on background can be scrolled =(
