### ISSUE TITLE
bug on railpadding

### ISSUE THREAD

**Issue by sylvain-** [inuyaksa/jquery.nicescroll#458]
Thanks for the good railpadding upgrade on last version,
but when you use railpadding: {top: 50} on html Tag, you can't scroll to the bottom of  the page, the 50px  of bottom was hidden, on chrome and firefox tested.

Thanks for all

**Comment by thebazel** [comment]
+1 Same problem

**Comment by thebazel** [comment]
Solution is patch:
comment or remove line: self.page.maxh -= (self.opt.railpadding.top + self.opt.railpadding.bottom);

in nicescroll.js source

**Comment by sylvain-** [comment]
Thanks for all of your work :)

**Comment by thebazel** [comment]
Some problems has appeared on my dynamic changed site. So I need to change more than one line of plugin code, and rewrote whole "else" block:

```javascript
else {
        self.page.h += (self.opt.railpadding.top + self.opt.railpadding.bottom);
        //self.page.maxh -= (self.opt.railpadding.top + self.opt.railpadding.bottom);  //removed
        self.rail.scrollable = true;
        if (self.page.maxh <= self.scrollvaluemax) 
        {
          self.rail.scrollable = false;
          self.hideRail();
        }
      }
```

In some cases you need to call `.resize()` method to update scrollbars on your page, if content inside scrollbar area has changed.
