### ISSUE TITLE
Cannot assign to read only property 'scrollable' of false on Chrome when horizrailenabled flase

### ISSUE THREAD

**Issue by h-sobhy** [inuyaksa/jquery.nicescroll#461]
If horizrailenabled is false in main JS or options, the Chrome browser returns 
"Cannot assign to read only property 'scrollable' of false "
jquery.nicescroll.js:2208 onResize

![untitled-1](https://cloud.githubusercontent.com/assets/3510226/5331699/abf6269e-7e3e-11e4-98f7-c2123b7f8360.png)

Version :3.60
Chrome Version 39.0.2171.71 m

**Comment by rmdydo** [comment]
I get this as well.

**Comment by babadofar** [comment]
+1

**Comment by orszaczky** [comment]
v3.5.6 does not have this issue

**Comment by PaykomanVll** [comment]
version 3.6.0 - i have the same problem :(

**Comment by kraenhansen** [comment]
+1 on version 3.6.0

**Comment by CreativForm** [comment]
I have that issue and fix error. Please add this in your code and Will work well.

On line 2199 remove existing code `self.rail.scrollable = true;` and add this:

`if (self.rail) self.rail.scrollable = true;`

After that on line 2228 remove `else if (!self.hidden && !self.railh.visibility) self.showRailHr();` and add this code:

`else if (self.railh && (!self.hidden && !self.railh.visibility)) self.showRailHr();`

That will fix problem with property scrollable.

@creativform

**Comment by inuyaksa** [comment]
Thanks, merged soon.
