### ISSUE TITLE
Shifting of cursor in textarea

### ISSUE THREAD

**Issue by kable7** [inuyaksa/jquery.nicescroll#462]
I found some bugs, first one in any browsers, if mouse pointer at bottom of textarea "on enter" scrollbar cursor shifts down and stretches the page, second mouse wheel doesn't work in Opera 12.17.
![untitled-1](https://cloud.githubusercontent.com/assets/9384079/5386662/c160bd0c-80f8-11e4-8331-5807a399c680.png)

**Comment by cehter** [comment]
I have the same problem with the textarea. Did you or anyone else fix it or has an idea why it occurs?

**Comment by kable7** [comment]
Unfortunately, no:( I used another plugin

**Comment by arzafran** [comment]
Same issue over here, which plugin did you use??

**Comment by kable7** [comment]
arzafran,  https://github.com/gromo/jquery.scrollbar/
