### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sylvain-** [inuyaksa/jquery.nicescroll#468]
Error on last version 
![error](https://cloud.githubusercontent.com/assets/10086268/5539505/a9898a78-8ac2-11e4-967f-30b7604ffc62.jpg)

**Comment by sylvain-** [comment]
It's an on 'resize' bug

**Comment by kaustubhkhare19** [comment]
i am facing same issue on ie 7 and 8.

**Comment by inuyaksa** [comment]
@kaustubhkhare19  please test last version.

**Comment by WinnieK** [comment]
Issue still remains - when nicescroll is active inside dropdown menu, this error appears. When inactive, no errors.

**Comment by inuyaksa** [comment]
Do you have an example to test?

**Comment by WinnieK** [comment]
Nevermind, found the issue, on my side - initialized twice in nested lists. However, in LTR direction no issues, in RTL direction throws an error if rail padding is set.

**Comment by rejhgadellaa** [comment]
I'm having the same issue. It's not really consistent though, sometimes it's fixed when I reload and then happens later again.

        app.vars.nicescroll[app.vars.currentSection] = $("#"+ app.vars.currentSection +" .content").niceScroll({
                zindex:50,
                cursorcolor:"rgba(0,0,0,0.54)",
                cursorwidth:"4px",
                cursorborder:"0px solid #fff",
                cursorborderradius:"4px",
                railpadding:{ top: 4, right: 4, left: 0, bottom: 4 }
            });
