### ISSUE TITLE
self is null

### ISSUE THREAD

**Issue by ssmathivanan402** [inuyaksa/jquery.nicescroll#469]
For New page loaded in the div, div expands. Here I get the console error for - Self is Null 
I use two place in the scroll bar using class selector. I try it using ID selector also. 

this.debounced = function(name, fn, tm) {
     ........
     .......
      if (!dd) {
        setTimeout(function() {
          var fn = self.delaylist[name];
          self.delaylist[name] = false;
          fn.call(self);
        }, tm);
      }
    };

**Comment by babadofar** [comment]
I had this happen when it tries to reference an element that no longer exists  ( due to timeout).

**Comment by aljohnrey** [comment]
Hi Guys
Can you help me with this error on my site "Uncaught TypeError: Cannot read property 'delaylist' of null"? Its pointing to the jquery.nicescroll?

Thank you

**Comment by inuyaksa** [comment]
Hi, which version do you use?
Please paste complete error line.

**Comment by aljohnrey** [comment]
-- version 3.6.0

**Comment by aljohnrey** [comment]
Can you help fixing this please? because I installed a wordpress plugin and that error is conflicting the plugin to not work

**Comment by inuyaksa** [comment]
Please try new version 3.7
