### ISSUE TITLE
Lovely plugin! One small issue

### ISSUE THREAD

**Issue by tengu3** [inuyaksa/jquery.nicescroll#471]
Wonderful plugin. Works like a charm. One small thing. When I set 'horizrailenabled: false', I get this error: Uncaught TypeError: Cannot assign to read only property 'scrollable' of false on line 2211. Hope you can fix it!

**Comment by orszaczky** [comment]
https://github.com/inuyaksa/jquery.nicescroll/issues/461

**Comment by inuyaksa** [comment]
Soon fixed
