### ISSUE TITLE
Keep up CDN

### ISSUE THREAD

**Issue by alidbg** [inuyaksa/jquery.nicescroll#472]
CDN latest version is old

http://cdn.jsdelivr.net/jquery.nicescroll/latest/jquery.nicescroll.min.js

Thanks.

**Comment by inuyaksa** [comment]
Just tagged. Sorry for delay.

**Comment by jimaek** [comment]
auto-updates are now enabled https://github.com/jsdelivr/jsdelivr/pull/4365 http://www.jsdelivr.com/#!jquery.nicescroll

**Comment by inuyaksa** [comment]
Great, Thanks!
