### ISSUE TITLE
Serious lag with animated contents

### ISSUE THREAD

**Issue by eidng8** [inuyaksa/jquery.nicescroll#474]
While trying out nicescroll on a test page I'm working on, I've experienced serious lag while my page contents are being animated.

In my page, I've a bootstrap Collapse control with 3 panels. Each of them expenses to about full height of the page, or a little more. During the expansion of any panel, the animation lags so much that I've seen them as expending in steps.

Not sure if I'm right, it seems nicescroll keeps updating during the course of any change made to the page. If this is the case, then I think there should be a pair (or so) of methods to allow us to temporarily turn off the tracking/updating, and while we are done change page contents, call the other method to re-enable and updates nicescroll.

**Comment by PlippiePlop** [comment]
Why don't you remove nicescroll .getNiceScroll().remove();and reattach it after completion of collapse.
Or try to .getNiceScroll().hide(); and after completion do .getNiceScroll().resize();

**Comment by eidng8** [comment]
Oops, never though I could use these ways, I'll try it out, thanks.

**Comment by 756gzdz5** [comment]
Should hide() and show() really work? For me it doesn't, as the mutation observer keeps triggering show() during the animation:

```javascript
mutations.forEach(function(mut){
    if (mut.type=="attributes") {
        return ($("body").hasClass("modal-open")) ? self.hide() : self.show();  // Support for Bootstrap modal
    }
});
```

**Comment by PlippiePlop** [comment]
You should try different methods. For example attaching nicescroll to the container AFTER the animation is completed. I really don't know what kind of 'animations' are running but normally you can do something like:

    $('#someSelector').on('animationend webkitAnimationEnd oAnimationEnd MSAnimationEnd', function(){ 
     $('#selector').nicescroll(...);
 });
