### ISSUE TITLE
Hi i have a problm with nicescroll and modal bootstrap.

### ISSUE THREAD

**Issue by hongquan09dth5** [inuyaksa/jquery.nicescroll#476]
i really like this js. but i have a problem with modal. i used tip getNiceScroll().hide and getNiceScroll().resize().show() in dynamic tab. so when a modal (bootstrap) slide up and close then function getNiceScroll().resize().show get a error "not defined". Can you help me for checking this issue. Thanks.

**Comment by PlippiePlop** [comment]
I have made a jsbin for you to try out:
http://jsbin.com/hubeno/1/

Let me know if this is what you are after.

**Comment by hongquan09dth5** [comment]
@PlippiePlop : Great example. it help me much for fixing other issues. Thanks you very much.

**Comment by fallenagus** [comment]
Just great, I was havving the same problem, thankyou @PlippiePlop.

**Comment by wakasann** [comment]
@PlippiePlop :+1: ,in the nicescroll v3.3.6,use your example,I change ·bModalBody.niceScroll().remove();·  to `bModalBody.getNiceScroll().remove();`,it is working,Thank you very musc!

**Comment by developersatish** [comment]
Hi, I have a issue with angular-bootstrap-ui modal pop up. its not working.
its working very fine with normal use, but when it comes with modal popup its not working.

**Issue in : In Modal pop (angular-bootstrap-ui)**
![image](https://cloud.githubusercontent.com/assets/2935852/20274023/4ae95a02-aab9-11e6-8b12-4c3550a228e5.png)

**Working fine: Normal use**
![normaluse](https://cloud.githubusercontent.com/assets/2935852/20274054/613cf372-aab9-11e6-8307-49036334aa62.PNG)
