### ISSUE TITLE
touch macbook

### ISSUE THREAD

**Issue by denidip** [inuyaksa/jquery.nicescroll#478]
Please correct the plugin work with the MacBook touchpad, thank you for your hard work, great plugin! ;)

**Comment by maciekmp** [comment]
up!

**Comment by dovy** [comment]
I use a touchpad... What problems do you have?

**Comment by maciekmp** [comment]
Do you know this magic scroll effect on osx? Inner window is still scrolling a while after user get up fingers from touchpad. Probably of this effect there is some jumps of inner window.
