### ISSUE TITLE
NiceScroll breaking browser jump to page start/end behaviour

### ISSUE THREAD

**Issue by roosmaa** [inuyaksa/jquery.nicescroll#480]
I have no idea why a lot of the internet is starting to user niceScroll plugin and I wouldn't care, but it is breaking default browser behaviour, which is annoying as hell.

On OSX with both Chrome and Safari, when you use Cmd+DownArrow (jump to page end) or Cmd+UpArrow (jump to page top) niceScroll interferes somehow and prevents the browser from doing what it's supposed to do and instead just scrolls up couple of lines.

Please fix this, before you more of the web is broken due to your plugin.

**Comment by comex** [comment]
It also breaks two-finger back/forward gestures.

**Comment by mreis1** [comment]
@roosmaa the answer to why is more people using this plugin is because not everyone has a mac like you do and native scrollbars look differently across  many platforms. Secondly, use or not use this plugin is up to the developer(s) who build/built the site(s) that you have coming across.

**Comment by roosmaa** [comment]
@mreis1 as mentioned before, I don't care how the scrollbars look, but breaking browser behaviour is bad. Web is broken enough, why break it even more.
