### ISSUE TITLE
Problems with niceScroll and <select>

### ISSUE THREAD

**Issue by cehter** [inuyaksa/jquery.nicescroll#497]
I want to add niceScroll to an multiple select element. 
It works, partly. But the "normal" scrollbar is still visible. 
Here an example: http://jsfiddle.net/75mpprjm/1/
Is it a bug or a implementation mistake from me?

**Comment by inuyaksa** [comment]
Hello, "select" element is not a supported div for nicescroll, but it seems to work too. (good!)
You can hide scroll with CSS.
Here you can find an example:
http://stackoverflow.com/questions/4531269/hide-vertical-scrollbar-in-select-element
