### ISSUE TITLE
Chrome: mouse wheel scroll issue

### ISSUE THREAD

**Issue by abrahamjagadeesh** [inuyaksa/jquery.nicescroll#499]
http://jsfiddle.net/k3tu16eh/

on chrome and when the page direction is 'rtl', the page cannot be scrolled when the mouse wheel is scrolled forwards, page scrolls only when the mouse wheel is scrolled backwards.

**Comment by RajsekarRaj17** [comment]
Debug this method in jquery.nicescroll.js file 
execScrollWheel(e, hr, chkscroll)

You can solve your problem.
