### ISSUE TITLE
NiceScroll 3.6 - Scroll bar not working on mouse wheel in chrome 38.

### ISSUE THREAD

**Issue by pawanrajput007** [inuyaksa/jquery.nicescroll#504]
NiceScroll 3.6 - Scroll bar not working on mouse wheel in chrome 38.

More Details: Actually scroll bar are working fine with all other browser and resolution but in chrome on 1280 *1024 resolution scroll bar not working with mouse wheel. if we use mouse wheel in window it not working but when we hover on scroll raill it working fine.

**Comment by IvoPereira** [comment]
+1, I'm having the same problem here.
