### ISSUE TITLE
Removing nicescroll from element

### ISSUE THREAD

**Issue by david-sabata** [inuyaksa/jquery.nicescroll#51]
I ran into some issues while trying to implement horizontally sliding navigation. That means there are side-by-side divs where only one is visible at the time and each one of them is scrollable using Nicescroll.

But when a div slides off the visible area, its scroll track still stays in the place.

I found `nicescroll.remove()` method, but it doesn't seem to do the job.
I even tried basic scenario where I initialized the nicescroll on an element and then removed it, but the track still stayed in the DOM and visible.

Could this be a mistake in my code? Is `remove` even supposed to be called from outside?
And most importantly - is there a way to completely remove all additional elements, bindings and all from an element?

**Comment by leo9223** [comment]
@rbrickyboy I think $("#scrollingDiv").getNiceScroll().remove(); is better. Works for me.
