### ISSUE TITLE
"Unable to get property 'delaylist' of undefined or null reference" error when the nicescroll container is removed

### ISSUE THREAD

**Issue by kissmd** [inuyaksa/jquery.nicescroll#511]
If the nice scroll is on a container what is added/removed dynamically from the dom, our users experiences sometimes the following error on console:
"Unable to get property 'delaylist' of undefined or null reference"

Fix is ready, i will create a pull request in a few minutes.

**Comment by tastepwalle** [comment]
Is this done? We are happily awaiting a fix^^

**Comment by kissmd** [comment]
it is not merged yet, please use the fix above if in need.

**Comment by lixinliang** [comment]
I have a idea about this problem. When I want to remove the container, I should remove the scrollbar first. So, I use `$('.wrap').getNiceScroll().remove()` to prevent it. Do it work ?
