### ISSUE TITLE
Parallax + Smooth Scroll issue on Chrome 44

### ISSUE THREAD

**Issue by thisisbbc** [inuyaksa/jquery.nicescroll#526]
Hi guys,

On our homepage there's a block with a parallax effect at speed 100 to make it look like it's fixed at its position.

If you use the scroll bar, the final effect is perfect. However, using mousewheel smooth scrolling, the translate function for the parallax block seems to have a different easing function than the smooth scroll easing function, so there's a small disparity in the UI experience.

I've tried to show you the problem in this screencast : https://drive.google.com/file/d/0B_-JNDqwSUVYUGNjOWpBOW1LdlU/view?usp=drivesdk

This problem does not happen in FF, only in Chrome.

**Comment by thisisbbc** [comment]
Whoever read these thing, we have fixed this problem using a different library from Kubik.

Link : https://wordpress.org/plugins/mousewheel-smooth-scroll/

**Comment by therockstar** [comment]
I am having same issue with nicescroll its working fine on Safari  firefox but on chrome the parallax block is juggling.

**Comment by Vnuuk** [comment]
Have the same problem in Chrome (47.0.2526.106). When you think you could fix this?
