### ISSUE TITLE
BUG: Bootstrap modal + nicescroll + changing DOM

### ISSUE THREAD

**Issue by RobbeR** [inuyaksa/jquery.nicescroll#528]
Hi,

I found a weird bug: 
- I have some automatic notifications, which are rotating in the bottom right part of the window
- I also have a bootstrap modal
- In this modal, I'm using this nicescroll (inited after the modal shows)

When the modal shows and the nicescroll initialized, it work fine for a few moment, but when the DOM changes in background (because of the automatic notification rotations), the nicescroll hides immediatelly. I found the code snippet which responsible for this behaviour, in the line number 1897:

if (mut.type=="attributes") {
                return ($("body").hasClass("modal-open")) ? self.hide() : self.show();  // Support for Bootstrap modal
              }

I commented this part out, and it works fine.

**Comment by f-dg** [comment]
I ran into the same problem. But in the latest version bug has been fixed, better either update nicescroll or copy paste the corresponding line (at now the line number is 2056)
