### ISSUE TITLE
NiceScroll 3.6 - Scroll bar not working on mouse wheel in brower(WebKit,IE).

### ISSUE THREAD

**Issue by robhz** [inuyaksa/jquery.nicescroll#529]
NiceScroll 3.6 - Scroll bar not working on mouse wheel in brower(WebKit,IE).

**Comment by inuyaksa** [comment]
Please try new version

**Comment by bear-wolf** [comment]
I have next files:
jquery.nicescroll_3.5.0.js
jquery.nicescroll_3.6.8.js

When I was version file 3.5.0 there is a ploblem http://prntscr.com/cf7oyv. 
With new version 3.6.8 this ploblem was fixed, but broken scroll of mouse whell.
For example: I open popup dialog and I have main scroll on body. 
Popup has select with nicescroll. So in version 3.5.0 select scrolling .... All ok;
BUT
In version 3.6.8 this problem repeated.
