### ISSUE TITLE
jQueryUI draggable scroll  Invalid  ?

### ISSUE THREAD

**Issue by zhump** [inuyaksa/jquery.nicescroll#530]
$(".container").draggable({ 
        scroll:true // niceScroll   mode Invalid 
});

**Comment by inuyaksa** [comment]
Please test this page and look in source (ui-nicescroll class)
http://nicescroll.areaaperta.com/test/jqueryui.html

New 3.6.7 release on developing.

**Comment by zhump** [comment]
i try test .....still have problems

http://jsfiddle.net/ofcwhzz4/

**Comment by zhump** [comment]
I made an example, nicescroll  can't achieve the effect of the native.....
I lost what configuration ?

look,
http://jsfiddle.net/vtgh8ohs/

Please help me ....

**Comment by inuyaksa** [comment]
No issues on windows with chrome/firefox.
Which os/browser do you use?

**Comment by zhump** [comment]
I mean, when I drag the container, the container can follow the scroll bar slide down. If you use nicescorll, would not have this effect....Please help me .........

**Comment by zhump** [comment]
![Uploading 1.gif…]()
![Uploading 2.gif…]()
