### ISSUE TITLE
Scrollwheel doesn't work anymore since chrome 46

### ISSUE THREAD

**Issue by mderiano** [inuyaksa/jquery.nicescroll#533]
It looks like scrollwhell doesn't work anymore since chrome 46. Tested with chrome 45 and it work well, but every computer with up to date chrome can't use it.

Thank you.

**Comment by milosdjakonovic** [comment]
I've checked with Chrome 46 / Windows 7 & latest version of niceScroll. Works as expected. What is the problem: scroll bar missing / mouse wheel scroll not working?

**Comment by mderiano** [comment]
Thank you, but I've found the solution. (mouse wheel scroll was not working, but the scroll bar was ok)

I had another div with "overflow: auto" inside the div with nicescroll (don't ask me why, I work on old code written by many people before me). When I remove "overflow: auto", everything is back to normal.
