### ISSUE TITLE
scroll inner scrolled element will break document scroll (chrome 46)

### ISSUE THREAD

**Issue by zhenyong** [inuyaksa/jquery.nicescroll#535]
https://jsfiddle.net/feipigzi/9wzub287/

scroll the div element will crash document scroll

**Comment by Oligo-Webdesign** [comment]
i have the same problem :/

**Comment by bnadeau** [comment]
It seems to work fine for me with Chrome Version 46.0.2490.71 m, what do you expect and what happens exactly?

**Comment by zhenyong** [comment]
Scrolling focus change to new element is too slow. When I am scrolling in the div, then change focus outside div, I must wait a few seconds to scroll whole document.
