### ISSUE TITLE
Reset Scroll

### ISSUE THREAD

**Issue by ernex24** [inuyaksa/jquery.nicescroll#536]
hello i have nice scroll in a template and i have an issue when i make scroll and i go out of the section ( using anchors) the scroll dont reset.  and i need the scroll can reset. when i enter to the area again.

**Comment by ernex24** [comment]
this is the link of the web the scroll is in the left in the profile area.

http://www.lime-xl.com/execo/mdst/html/demo1/index.html?p=home

**Comment by bnadeau** [comment]
Did you try calling the following when you transition out?
```javascript
$('#team .team-info-wrapper').getNiceScroll().doScrollTop(0);
```

**Comment by ernex24** [comment]
I put the function here but its not working, do you know another solution? thanx
![ssss](https://cloud.githubusercontent.com/assets/15176182/10727181/28b9351c-7bd8-11e5-9dcd-da78c2ec0ef7.PNG)

**Comment by bnadeau** [comment]
I can't really tell when that line is executed. You want to execute that line when you click the right double arrow to exit your profile view.

**Comment by mshahin364** [comment]
You can use jquery scrollTop/scrollLeft method. It's working for me.

$('#team .team-info-wrapper').scrollTop(0);
$('#team .team-info-wrapper').scrollLeft(0);

**Comment by zhenxianluo** [comment]
because you less a 0!
$('#team .team-info-wrapper').getNiceScroll(0).doScrollTop(0);
