### ISSUE TITLE
How to detect scroll has started?

### ISSUE THREAD

**Issue by ibrahimmumcu** [inuyaksa/jquery.nicescroll#542]
Is there any method that I can detect scroll started and stopped?

**Comment by kajmagnus** [comment]
Yes, `niceScroll.scrollstart(function(event) { ... }))` but it doesn't work for me. Only `.scrollend(...)` works. Is this a bug?

Here you'll find `.scrollstart(...)`:
https://github.com/inuyaksa/jquery.nicescroll/blob/af737e0f2f6d0f22c66f65809b0c93e396216e51/jquery.nicescroll.js#L2542

**Comment by kajmagnus** [comment]
You can use jQuery instead. This works for me, at least right now when testing in Chrome:
```
    // first:
    // var $viewport = $(...);
    // $viewport.niceScroll(scrollableElem, { ... });

    $viewport.on('scroll', function(){
      console.log('$ scroll');
    });
```

**Comment by inuyaksa** [comment]
Please test with this page.
http://areaaperta.com/nicescroll/test/scroll.html

**Comment by ibrahimmumcu** [comment]
niceScroll.scrollstart works for me, thank you!
