### ISSUE TITLE
Nicescroll not compatile with jquery.mousewheel anymore

### ISSUE THREAD

**Issue by kazelone** [inuyaksa/jquery.nicescroll#546]
Nicescroll used to be working alongside jquery.mousewheel. By that, I mean that if you hooked a mousewheel event on the same element that had a nicescroll, it was working as intended; if you prevented the event, nicescroll didn't scroll, but if you let the event through, nicescroll's mousewheel was working properly.

Since a recent nicescroll version (haven't pinpointed the exact one, but most likely > 3.6.x) this isn't working anymore; simply having a mousewheel handler attached break nicescroll's scrolling, even if you don't prevent the event.

**Comment by inuyaksa** [comment]
Do you have any example to test?
