### ISSUE TITLE
Hi: Browserify  require  fail

### ISSUE THREAD

**Issue by fegg** [inuyaksa/jquery.nicescroll#548]
my english is not well = =.

1.I use  nicescroll :

var $ = require('jquery');
var nicescroll = require('../lib/jquery.nicescroll');  // path haven't  error,  because npm can't install.

2.I find nicescroll haven't return object, so, nicescroll is undefined is normal .  but, I want to know , which use the nicescroll.  

I think required, I can use it $.fn =>  $('.wrap').nicescroll. but  not well. help = =.

**Comment by inuyaksa** [comment]
It's correct loading nicescroll lib it not instance an object.
You need $("html").niceScroll() to activate scroll on page.
Watch the examples:
http://areaaperta.com/nicescroll/demo.html

**Comment by fegg** [comment]
@inuyaksa thanks,  your mean to can't use nicescroll by require's method ?  only use script before insert body?

**Comment by fegg** [comment]
I use browserify-shim.  finnally  not  solution  this  question....   which use   browserify-shim   nicescroll，and   use   require('nicescroll')

**Comment by inuyaksa** [comment]
Sorry, why do you use browserify?

**Comment by fegg** [comment]
@inuyaksa beacuse I want to load js by CMD method.  

exp:

var $ = require("jquery");
require('../lib/jquery.nicescroll');

var Mock = require('mockjs');
var Medium = require('medium.js');

var select = require('../common/select');
var keyCode = require('../common/keycode');
var clip = require('../index/clip');

....
  $('body').nicescroll();
   my code
....

I haven't use webpack....But google's anwser, can  accord to browserify-shim to use  jquery plugin.  I haven't success. = = ~

**Comment by inuyaksa** [comment]
Sorry I don't know how browserify works.

In plugin code, some contributor add jcommon compatibility with this line, can you check if it needs some fix?

    module.exports = factory(require('jquery'));

**Comment by bnadeau** [comment]
Hi. I added the Browserify support line, maybe I can help. I have never used browserify-shim, but I've been using jquery.nicescroll with Browserify.

@fegg The way I require nicescroll is that I define it in package.json dependencies as:
```
"jquery-nicescroll": "https://github.com/inuyaksa/jquery.nicescroll/archive/3.6.6.tar.gz",
```

Then I require it after requiring jquery with:
```
require("jquery-nicescroll");
```

You don't need the shim for nicescroll as the latest version supports Browserify.
