### ISSUE TITLE
jQuery NiceScroll Broke Input Labels

### ISSUE THREAD

**Issue by NinjaKC** [inuyaksa/jquery.nicescroll#551]
In a project I am working on, I heavily use nicescroll as well as another feature which I refer to as Radio & Checkbox Buttons, which is comprised of only html label, with an input and div inside, and some css magic to turn radio & checkboxes into nice looking buttons.

Which can be seen here, http://jsfiddle.net/y4tzfk0g/

If I have a div which has nicescroll enabled on it, and inside that div I have a label which has an input inside it, and the scrollbar is 'active' on the outer div. And you touch with your finger on the label's, the label will NOT focus on the input. In the case of my above buttons, this means the checkbox & radio buttons are not changed, and further means that the overall project (which relies on touch) fails.

You can see this at the following jsfiddle, http://jsfiddle.net/p4cc03e7/

Note, that at the vary bottom of the display window, you can see a normal text input wrapped in a label with nothing fancy done to it. The label says "CLICK THIS LABEL TO TEST A NORMAL INPUT", if you click this with a mouse the expected behavior works, if you touch it with your finger however (on desktop w/ touch or mobile) you will see that you will not be focused on the text input field.  The inside of the input says "Click the input field to see it can still be focused normally", if you click or touch this field it focuses as expected.

In conclusion, the following code will break when TOUCHED with a finger but will work when CLICKED with a mouse, assuming the label on the inside overflows outside of the #NiceScroll div, the label will no longer focus the input inside itself. as one would expect. If scrollbars are not active (label does not overflow out of the div to create a scrollbar) then everything works fine.

<div id="NiceScroll">
    <label> SOME TEXT IN THE LABEL <input /> </label>
</div>

If anyone in the community can help solve this that would be great, as I have tried solving the issue within nicescroll myself for awhile now, and am still not understanding why it is happening. It seems like a touch on nicescroll, fires the touchmove even when I don't actually move my finger, and that itself is making it so the click events do not fire on the labels.

I have found that this issue happens on (touch) Desktop: Chrome, IE, Opera, & Mobile: Chrome, Opera, Firefox. Though it seems Desktop Firefox does not fire touch events the same, and works flawlessly. I've tried to identify why firefox works and the others don't, and can only come down to Firefox doesn't fire touch events. Which I have tested over at http://jsfiddle.net/cpUsA/4/

Thanks For Any Help or Guidance! If I can fix this issue I will contribute back where ever I can.

**Comment by NinjaKC** [comment]
After a few more final attempts, I have solved this for most browsers. It seems however our good ol' buddy and pal IE [and Edge] are still needing some more love to get this to work. If I can fix it, I will contribute my changes, except they are done on 3.6.0, not 3.6.6. It seems 3.6.6 has a whole new issue all together with regards to labels (nicescroll limits the click event it seems to one time per scroll bar, so the labels are only clicked once and then no other label on that scrolling div works)

**Comment by NinjaKC** [comment]
Ok so for IE, I was able to at least get half the desired affect by adjusting line 1524, from 

self.onclick = (cap.isios) ? false : function(e) {

to

self.onclick = (cap.isios || cap.isie11) ? false : function(e) {

Though this allows the labels to work, the slight issue with this, is that the scroll bar turns on as soon as you touch (unlike other browsers, it seems to be delayed just a bit). With this, it means that when the scrollbar is turned on, and you release your finger, the label is clicked, when it should be ignored while the scrollbar is turned on, and not ignored (and working) when the scrollbar is off. Since the scrollbar turns on earlier then other browsers in IE, it seems their is no way to determine the different states without measuring the distance of the move (which I feel is hackish, while I assume you guys already account for this somewhere for other browsers, I am unable to figure that part out it seems)

Any help is appreciated, thanks.

**Comment by inuyaksa** [comment]
Thanks, on helping me.
Can you test with developing version, select branch rtl-mode?
