### ISSUE TITLE
Css Transitions

### ISSUE THREAD

**Issue by crash21** [inuyaksa/jquery.nicescroll#552]
Hello,

I have the following bug:

When I zoon-in/out a page which uses css transitions the scrollbar is on wrong place. What I think is that nicescroll fires resize event millisecond after it happens and calculates new dimensions which the millisecond after are not the final as transitions still in progress. Any way to put some delay and hide scrollbar until transition is over and then re-apear it?

Anyone having same problem?

**Comment by inuyaksa** [comment]
Please test developing branch "rlt-mode".
Let me know if it works.
