### ISSUE TITLE
NIce Scroll doesnt work on Window Surface IE Edge

### ISSUE THREAD

**Issue by SalmanZafar214** [inuyaksa/jquery.nicescroll#555]
hi 
i used Nicescroll and it works fine but recently i m facing an issue
on Window surface with IE Edge [IE 11] i m not able to use scroll and that happens with touch too.

Even demo http://areaaperta.com/nicescroll/demo.html provided by site also not working
can some one help me ?? 
Any help will be appreciated

**Comment by StephanBijzitter** [comment]
I think this may very well be related to: https://github.com/noraesae/perfect-scrollbar/pull/401

**Comment by inuyaksa** [comment]
Fix soon.
Related to #581

**Comment by BernhardKoenig** [comment]
I tested 3.6.8 and it works on Internet Explorer, but not in Edge. I did a little bit of debugging and it seems the detection of Edge does not work with this line:

`d.isieedge = ("msOverflowStyle" in _el);  // IE Edge`

This returns false in Edge (Win 10 / Desktop version, at least).

**Comment by imacks** [comment]
opera works on surface 4 pro.
