### ISSUE TITLE
Resize (RangeError: Maximum call stack size exceeded.)

### ISSUE THREAD

**Issue by estevaosa** [inuyaksa/jquery.nicescroll#563]
Mello guys, the last version still have a problem with resize. Do you know something about it?

RangeError: Maximum call stack size exceeded.

[Error] RangeError: Maximum call stack size exceeded.
    replace
    camelCase
    access
    data
    scrollTop
    getScrollTop
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos
    scrolling
    doScrollPos

tas

**Comment by bradrich** [comment]
+1. Have not had a problem with this project at all except for this.

**Comment by amolinaalvarez** [comment]
+1. Same problem!

**Comment by inuyaksa** [comment]
It seems related to #578

**Comment by rraya** [comment]
one more with the same problem...

**Comment by inuyaksa** [comment]
I'm working for a major rewriting on code to have a solid plugin. I hope soon.

**Comment by blacksunset** [comment]
+1

**Comment by Coobers** [comment]
@inuyaksa Is it possible to fix it before mayor release or give a hint how to patch it up in best manner? it's a mayor issue on production.

**Comment by inuyaksa** [comment]
Which version do you use?
Can I have a demo to test this issue?
