### ISSUE TITLE
MutationObserver. IE11 crashes

### ISSUE THREAD

**Issue by ronar** [inuyaksa/jquery.nicescroll#568]
Hi! We've stumbled upon a problem with scroll.
We're using angular to build our software and your scroll fits right in. But with this new feature MutationObserver, browser IE 11 is crashing gracefully. It happens in certain cases when we change the DOM (it happens in digest cycle of angular), in dynamic sidebar that moves in/out. Is there a any way to overcome this problem? Because before that we've changed scroll three times already. And your scroll is pretty good. I found out that before version 3.2.0 there wasn't MutationObserver. But bower can't find the version. Thanks in advance.

**Comment by inuyaksa** [comment]
Do you have some example to test?

**Comment by ronar** [comment]
I've tried to reproduce it in plunkr, but with no luck. Have to change logic completely to get it to work, so now it's working stable. This bug is in IE for sure. I thought it might be possible to put some workaround.

**Comment by inuyaksa** [comment]
Disabling bootstrap code on IE11 - test 3.6.8
