### ISSUE TITLE
Missing npm package

### ISSUE THREAD

**Issue by basvandenheuvel** [inuyaksa/jquery.nicescroll#569]
Why is nicescroll not on NPM?

**Comment by inuyaksa** [comment]
Why not? :)
How can I submit to npm?

**Comment by basvandenheuvel** [comment]
@inuyaksa nice :)

See:https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by inuyaksa** [comment]
Thnaks. Package published: https://www.npmjs.com/package/nicescroll

**Comment by basvandenheuvel** [comment]
@inuyaksa  looks like you succeeded?

**Comment by jlowery457** [comment]
Any traction on this?

**Comment by laggingreflex** [comment]
@inuyaksa what issues were you running into? I was able to publish just fine without any issue (I published [laggingreflex-nicescroll](https://www.npmjs.com/package/laggingreflex-nicescroll) for checking, which I've deleted now to avoid any future confusion). 

I can try if you like, give me access on npm: https://www.npmjs.com/package/nicescroll/access (add my username there)
