### ISSUE TITLE
How to remove lagging on scroll while using jquery nicescroll?

### ISSUE THREAD

**Issue by iamfaiz** [inuyaksa/jquery.nicescroll#572]
I am using jquery nicescroll plugin to add, well, nice scroll to my website. This website was working pretty nicely but now for reason ( I can't figure out ) it is not. It is lagging. I have no idea how I can debug it. Maybe it is because I am using a log of high resolution images. But if I remove the nicescroll plugin, the scroll works nicely. Can somebody tell me what is wrong?

Here is the website: http://iamfaiz.github.io/multi-x/

Note: Please tell me what other information should I provide for you guys to help me?

**Comment by Hugao** [comment]
It also happens to me on 3.6.7 and up, but only during load, after that it's smooth.

**Comment by inuyaksa** [comment]
I'm working for a major rewriting on code to have a solid plugin. I hope soon.

**Comment by metodribic** [comment]
Any update on this ?

**Comment by inuyaksa** [comment]
Version 3.7.4 made scroll very smooth and cpu saving
