### ISSUE TITLE
Works well  but all my links does'nt works on Firefox/Android

### ISSUE THREAD

**Issue by pierrewebmaster** [inuyaksa/jquery.nicescroll#573]
Thank you for this very nice pugin.
But as said on the title, all the links and navbar does'nt works only on Firefox/Android.
My web site is based on Bootstrap cleaned of all that is useless to me. 
I tried to change z-index but without succes.
Do you have any idea where does the problem?
Thank you for your help

**Comment by hosamalzagh** [comment]
+1 me to i have same pug and addition <a href> return false dont work

**Comment by MakeCodeNotCss** [comment]
with {preservenativescrolling: true, touchbehavior:false} works fine.
