### ISSUE TITLE
3.6.7 not working on ios or android

### ISSUE THREAD

**Issue by BernsteinA** [inuyaksa/jquery.nicescroll#574]
But 3.6.6 works fine.

**Comment by onapp-phill** [comment]
Confirmed not working on 3.6.7 but works fine on 3.6.6

**Comment by BernsteinA** [comment]
@onapp-phill thanks for confirming.

**Comment by gr1m** [comment]
same with 3.6.8 - not working on ios or android

**Comment by RfpRZ9WPsB** [comment]
Confirmed, not working on Android , version 3.6.8

**Comment by inuyaksa** [comment]
I'm working for a major rewriting on code to have a solid plugin. I hope soon.

**Comment by vbguyny** [comment]
Any update on this?

**Comment by acs-ferreira** [comment]
No update at this time?

**Comment by inuyaksa** [comment]
#626
