### ISSUE TITLE
touchbehavior: false is not working on v3.6.7

### ISSUE THREAD

**Issue by paxpelus** [inuyaksa/jquery.nicescroll#575]
All of the sudden the touchbehavior is not working anymore. I need to have touchbehavior:false becuase I use some drag &drop functionality but this option is not respected anymore.

Besides the above, I can now see in console log 

mousedown undefined
jquery.nicescroll.min.js:1 touchstart  mousedown
jquery.nicescroll.min.js:1 touchend: DIV

**Comment by inuyaksa** [comment]
I'm working for a major rewriting on code to have a solid plugin. I hope soon.
