### ISSUE TITLE
Timeouts & using on dynamic DOM Elements: "Uncaught TypeError"

### ISSUE THREAD

**Issue by JD-Robbs** [inuyaksa/jquery.nicescroll#579]
Hi there, love the plugin!

I am using it in conjunction with an MVVM framework - binding it to my HTML nodes dynamically.

Due to the fact that niceScroll uses timeouts in some places, it can happen that elements don't exist anymore by the time an event is fired.  Here's my specific problem - with 240ms being the culprit:

The following line:

    https://github.com/inuyaksa/jquery.nicescroll/blob/master/jquery.nicescroll.js#L2371

Outputs the following error:

    Uncaught TypeError: Cannot read property 'show' of null

**Comment by aMUSiC** [comment]
Confirming that this indeed is an issue. Very prominent in angular apps where elements show and hide dynamically a lot.

**Comment by JD-Robbs** [comment]
One simple option could be to simply check for the element's existence before using its properties - maybe?

**Comment by inuyaksa** [comment]
related #583

**Comment by JD-Robbs** [comment]
@inuyaksa - fantastic - that solved it for me!

Just one thing I noticed: it looks like the unminified "jquery.nicescroll.js" is missing from the 3.6.8 build when downloading it via bower.
