### ISSUE TITLE
MutationObserver lag (option to disable?)

### ISSUE THREAD

**Issue by gbggit** [inuyaksa/jquery.nicescroll#580]
The idea with using MutationObserver is great but not always.

Consider the situation when nicescroll is binded to the html tag and then each elem change (like class toggle, attr update, etc.) will trigger nicescroll refresh, which on a page with a lot of sliders and animations could cause serious lag.

I have disabled it manually by setting `ClsMutationObserver = false`, but it will be nice to have an option for that.

btw. **nicescroll** is maybe the best and most advanced scroll plugin I've used so far

**Comment by inuyaksa** [comment]
New option "disablemutationobserver" coming...
