### ISSUE TITLE
Xbox One IE Edge browser can't scroll anywhere

### ISSUE THREAD

**Issue by jinglejangle** [inuyaksa/jquery.nicescroll#581]
When I use niceScroll.js (jquery.nicescroll 3.6.7) on my site (which works great on phone/desktop thank you)
I can not scroll anywhere on the Xbox One IE browser. 
Disabling niceScroll makes me able to scroll again.

**Comment by StephanBijzitter** [comment]
I think this may very well be related to: https://github.com/noraesae/perfect-scrollbar/pull/401

**Comment by inuyaksa** [comment]
Trying a fix, I don't own real hw to test. I hope this works ;)
3.6.8

**Comment by Hugao** [comment]
It also doesn't work on IE Windows Phone, version 3.6.6

**Comment by inuyaksa** [comment]
I'm working for a major rewriting on code to have a solid plugin. I hope soon.

**Comment by iktech1** [comment]
I have the same problem. The newest version is better, but doesn't work as nice as on a android mobile. :-(
