### ISSUE TITLE
niceScroll is undefined

### ISSUE THREAD

**Issue by florinbardosi** [inuyaksa/jquery.nicescroll#585]
Using 3.6.8, niceScroll function is undefined

var niceScrolledPanel = $(panelClass);
$(document).ready(function () {
     niceScrolledPanel.niceScroll({cursoropacitymax: 0});
});

**Comment by kotmatpockuh** [comment]
same issue...

**Comment by barrychapman** [comment]
same here too

**Comment by barrychapman** [comment]
@inuyaksa  was this resolved?

**Comment by inuyaksa** [comment]
Sorry, issue archived becoming too old.
Do you have this issue in your code?

**Comment by barrychapman** [comment]
Yes

**Comment by inuyaksa** [comment]
Do you have a code to test?
It's important you load nicescroll js library before caching DOM elements, as this issue
`var niceScrolledPanel = $(panelClass);`
