### ISSUE TITLE
smoothscroll false doesn't work when touchscroll true

### ISSUE THREAD

**Issue by ginoxc** [inuyaksa/jquery.nicescroll#586]
Hey! Thank you for this plugin, it's super cool.

Is there any way to use touchbehavior and smoothscroll false at the same time?

{smoothscroll:false,touchbehavior:true}

I want the touch activated but I dont want the delay/momentum activated. I cant make it work.

Is there any way around it? I can't find it

Thank you!

**Comment by inuyaksa** [comment]
Try last version
