### ISSUE TITLE
Rails attach to the wrong element when a container element is used and 'hardware-accelerated' scrolling is not used

### ISSUE THREAD

**Issue by rjgotten** [inuyaksa/jquery.nicescroll#587]
When a wrapping content element is used and hardware-accelerated scrolling is not used --- either because it is unavailable, or because it is explicitly disabled with a `hwaccelerated:false` option ---, then nicescroll attaches the rail elements to the _document body_ instead of the element itself.

There seems to be a basic failure in supporting the case of a content element paired with hardware-accelarated scrolling disabled. The nested content element should be given `overflow:hidden` and should become the scrolled surface in this case, so that the nicescroll element itself can serve as a viewport that can hold the scrollbars with absolute positioning without them being scrolled out of view.

**Comment by inuyaksa** [comment]
Fixed >= 3.7.4
