### ISSUE TITLE
Scroll flickers

### ISSUE THREAD

**Issue by ronar** [inuyaksa/jquery.nicescroll#588]
Ubuntu 14.04, Google Chrome 46.0.2490.71.
https://plnkr.co/edit/u8BsADQGno0scnQ0PNgO?p=preview

**Comment by abenchi** [comment]
+1

**Comment by masandoval** [comment]
I was able to fix this issue for my project by modifying the resize test in the document body MutationObserver callback. It's calling the resize function whenever the document.body height doesn't match the scrolling container's height, which doesn't take into account things like a toolbar laid out underneath the scrolling container.

At line 1973:

        if ((!self.isie11) && (ClsMutationObserver !== false)) {  // IE11 crashes  #568
          self.observerbody = new ClsMutationObserver(function(mutations) {
            mutations.forEach(function(mut){
              if (mut.type=="attributes") {
                return ($("body").hasClass("modal-open") && $("body").hasClass("modal-dialog") && !$.contains($('.modal-dialog')[0],self.doc[0])) ? self.hide() : self.show();  // Support for Bootstrap modal; Added check if the nice scroll element is inside a modal
              }
            });  
    -            if (document.body.scrollHeight!=self.page.maxh) return self.lazyResize(30);
    +
    +            // if (document.body.scrollHeight!=self.page.maxh) return self.lazyResize(30);
    +            if (self.me.clientWidth!=self.page.width || self.me.clientHeight!=self.page.height) {
    +              return self.lazyResize(30);
    +            }
          });
          self.observerbody.observe(document.body, {
            childList: true,
            subtree: true,
            characterData: false,
            attributes: true,
            attributeFilter: ['class']
          });
        }

**Comment by inuyaksa** [comment]
Thanks for hits!
I'm working for a major rewriting on code to have a solid plugin. I hope soon.

**Comment by ronar** [comment]
Worked for me as well

**Comment by luka-sakun** [comment]
Unfortunately the fix doesn't work.
Here is an issue - https://github.com/inuyaksa/jquery.nicescroll/issues/632

**Comment by inuyaksa** [comment]
Fixed on 3.7.0, please can you check if resolved?
