### ISSUE TITLE
nicescroll not work after jquery clone dom

### ISSUE THREAD

**Issue by fegg** [inuyaksa/jquery.nicescroll#589]
Hi, 

My problem's I use jQuery .clone(true) method product a new dom, new dom's nicescroll not work, but this dom use getNiceScroll() it return NiceScroll Object.

// view nicescroll object
`$newDom.getNiceScroll()`
// return object
`NiceScrollArray {0: NiceScrollClass, length: 1, name: "nicescrollarray"}`

I want to destory new dom nicescroll, after re-bind nicescroll.

why clone(true) can't clone nicescroll? sos...  thanks...

**Comment by inuyaksa** [comment]
Reapply nicescroll to cloned div
