### ISSUE TITLE
Problems with touchbehavior:false in version 3.6.7 & 3.6.8

### ISSUE THREAD

**Issue by paxpelus** [inuyaksa/jquery.nicescroll#590]
I use the following code

$(".myDiv").niceScroll({
     scrollspeed: 80,
     mousescrollstep:100,
     touchbehavior: false,
     cursoropacitymin:0.2,
     cursorwidth: 10,
     zindex: 1000
   });

On version 3.6.6 the touchbehavior was correctly disabled
On version 3.6.7 & 3.6.8 the touchbehavior:false parameter is ignored and touchbehavior is enabled by default.

Versions 3.6.7 & 3.6.8 are nice because horizontal scrolling (using SHIFT) finally works but it destroys my layout because of touchbehavior (I use drag & drop features in the nicescroll area which do not work anymore because touchbehavior: true)

**Comment by dorrotman** [comment]
Thanks for the post, I had that problem too. Downgraded to 3.6.6 for now.
