### ISSUE TITLE
Conflict with countdown seconds

### ISSUE THREAD

**Issue by Codevz** [inuyaksa/jquery.nicescroll#591]
Hi, 

Thanks for this great scripts, Recently i found there is small conflict between jQuery.Countdown and Nicescroll script, With each countdown seconds, nicescroll trigger display block / none

You can check here: https://vid.me/2VB9

Is there any quick fix for this ?!

Thanks

**Comment by inuyaksa** [comment]
Fixed on version >= 3.7.4
