### ISSUE TITLE
mousewheel scrolling not working

### ISSUE THREAD

**Issue by dvinodeluru** [inuyaksa/jquery.nicescroll#593]
Hi, 

I am applying nicescroll in various components on single page with same class name, loses the mouse wheel behavior if body is set to hidden and div having scrollbars.

$(".scrollText").niceScroll({ cursorborder: "", cursorcolor: "#ec008c", boxzoom: false, dblclickzoom: false, gesturezoom: false, cursorwidth: "7px", enablemousewheel:true, horizrailenabled: false }); 

any advice to fix this

**Comment by dvinodeluru** [comment]
Nice Scroll bar functionality was applied to the modal dialog box containers, found the work around to issue. The failure cause because of "body" scrolls are disabled to have a fixed header and container get scrollbar, when bootstrap modal dialog is opened the nicescroll is not working due to background container got scrolling not body, by tweaking container scrollbar get disabled then the nicescroll functionality works. 

The next weird issue in other page is Nice Scroll bar losses its focus on off when there are links to click and scroll moves to first position.

Any help would be appreciated

thanks
Vinod

**Comment by huang-x-h** [comment]
@dvinodeluru see PR #600
