### ISSUE TITLE
Nicescroll Horizontal ScrollBar Issue [Version - 3.6.8]

### ISSUE THREAD

**Issue by krng** [inuyaksa/jquery.nicescroll#598]
Hi I am using Nice-scroll plugin and have updated it to the latest version available.
I am trying to implement the horizontal scrolling using this plugin. On browser resize the nice scroll bar is jumping above its fixed position. I tried searching for horizontal nice scroll examples but dint find any to replicate the issue . Could you please help me out with this.

Attached are the snapshots...

https://cloud.githubusercontent.com/assets/18589343/14700449/4988013a-07bd-11e6-8ad4-af0d5fc0e347.PNG

https://cloud.githubusercontent.com/assets/18589343/14700456/521d954e-07bd-11e6-8654-0eb7587cf185.PNG

Thanks

**Comment by bradrich** [comment]
+1.

**Comment by bradrich** [comment]
@krng This seems to be happening no matter what efforts you make. I have tried to set the height of the container, monitor that height on window resize, etc. Nothing seems to change it. I also noticed that on window resize, the scrollbar jumps around all over the container. If it wasn't for Google Chrome's element scroll into view, I wouldn't even be able to find it.

**Comment by krng** [comment]
Hi,

Any solution for this horizontal nicescroll issue ??

Thanks

**Comment by Swathi567** [comment]
i am facing same issue.

Is there any solution?

Thanks

**Comment by PirunSeng** [comment]
+1
I've set the niceScroll() on my table responsive dev. I'm also have a sidebar on the left collapse/expand.
Sometimes the horizontal bar cannot reach the beginning of the table, it seems there is a small padding left on the table or div. Anyway, it sometimes overlaps the wrapper div.
Are there any solutions yet?
