### ISSUE TITLE
zoomico.png for old versions

### ISSUE THREAD

**Issue by pvnr0082t** [inuyaksa/jquery.nicescroll#605]
Hi @inuyaksa ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. We want to add `zoomico.png` for **v3.5.1** and **v3.5.4** but there are no tagged releases for these two versions. Are the `zoomico.png` in **v3.5.1** and **v3.5.4** same as the newer version? If not, could you provide us the `zoomico.png` for these versions?

https://github.com/cdnjs/cdnjs/pull/7916
https://github.com/cdnjs/cdnjs/issues/4218

**Comment by inuyaksa** [comment]
Please , get current release

**Comment by pvnr0082t** [comment]
@inuyaksa Do you mean the `zoomico.png` of current version can be used in v3.5.1 and 3.5.4? We will host all versions as you can see in https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery.nicescroll, but we don't know where to get `zoomico.png` for v3.5.1 and v3.5.4. Thank you.

**Comment by inuyaksa** [comment]
Hi, correct icon is compatible, only a compression optimization about versions.
Better, you can use 3.4.0 version from here: https://code.google.com/archive/p/jquery-nicescroll/downloads?page=1
I'll search on my archive if I a have those releases.
