### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by antoniogarcez** [inuyaksa/jquery.nicescroll#608]
Hi,

I have a problem with plugin niceScroll, when I am trying to select text in textarea or drag (I have a draggable area created with jquery-ui) an element appears this error:

`Uncaught RangeError: Maximum call stack size exceeded
[Symbol.replace] @ (program):405
replace @ (program):134
n.extend.camelCase @ jquery-1.12.3.min.js:2
R @ jquery-1.12.3.min.js:3
n.extend._data @ jquery-1.12.3.min.js:3
n.extend.queue @ jquery-1.12.3.min.js:3
n.extend.dequeue @ jquery-1.12.3.min.js:3
(anonymous function) @ jquery-1.12.3.min.js:4
n.extend.each @ jquery-1.12.3.min.js:2
n.fn.n.each @ jquery-1.12.3.min.js:2
n.fn.extend.stop @ jquery-1.12.3.min.js:4`

**Comment by t-yng** [comment]
I had same error with same situation when I set railpadding top or bottom.

**Comment by antoniogarcez** [comment]
In my case, I had to change Nicescroll to another library.
