### ISSUE TITLE
Problem when element in my tree is hover scrollbar hide

### ISSUE THREAD

**Issue by EnergyTeam** [inuyaksa/jquery.nicescroll#609]
Hello everyone!

I have a problem with nicescroll, I have a tree where each node on mouse takes a hover event where the node is highlighted.

My problem is that even setting the nicescroll with autohidemode: false the nicescroll take param display:none; each time I hovered a node. 

Is there some other parameter that can be set?

With nicescroll versione 3.5.8 there isn't this problem, but in old version there isn't param railhoffset and i need it!

**Comment by EnergyTeam** [comment]
I debug the lib...

The problem is at line 1981..
if (document.body.scrollHeight!=self.page.maxh) return self.lazyResize(30);

the lib enter in this if, and the funciont lazyResize hide the scrollbar because  hasWrapper is false.. Why???

**Comment by alexandr-bbm** [comment]
Had a similar issue, as @EnergyTeam and my problem was solved by rewriting this line as it mentioned [here]( https://github.com/inuyaksa/jquery.nicescroll/issues/588)

**Comment by inuyaksa** [comment]
#588
