### ISSUE TITLE
Keep scrollbar visible until mouse leaves the scrollable div

### ISSUE THREAD

**Issue by IsaacHub** [inuyaksa/jquery.nicescroll#610]
Hi everyone,

Could anyone tell how to Keep scrollbar visible until mouse leaves the scrollable div.

If I mouseover a nicescroll-applied div then scrollbar appears and fades out within a second. The visibility of scrollbar is initiated on scroll-start, but I don't like it, the scrollbar should be visible until mouse leaves the div/element.

If I set `cursoropacitymin:` to  `1` in `jquery.nicescroll.js` , then scrollbar is visible forever, but that's not what I want.

Is there an option or a workaround??

**Comment by inuyaksa** [comment]
Sorry for delay.
You need to use this option:
autohidemode:"leave"
