### ISSUE TITLE
Nicescroll not working in IOS 9+

### ISSUE THREAD

**Issue by snazaresn** [inuyaksa/jquery.nicescroll#611]
Hello,

We are facing issues in IOS9+ for nicescroll, please let us know if there is any  workaround.

Thanks and Regards,
Shailesh

**Comment by gauravparashar12** [comment]
Yes , I am also facing the same issue on ipad

**Comment by nickdekruijk** [comment]
Same here... Any alternative scrolling plugin suggestion? Websites are broken now. Workaround I use is to disable nice scroll on touch devices.

**Comment by stephanvierkant** [comment]
The best alternative: don't use this plugin. All browsers have working scrollbars nowadays.

**Comment by nickdekruijk** [comment]
'Working' doesn't mean they are nice to look at. I use nice scroll mainly because I want a minimal design for the scrollbars. Just a small dot on a tiny hairline for example.

**Comment by raknjak** [comment]
You might want to try Perefect Scrollbar. It's not perfect though :p
https://github.com/noraesae/perfect-scrollbar

**Comment by nickdekruijk** [comment]
I found perfect scrollbar last week actually and I like it a lot so far
