### ISSUE TITLE
Bug in bower.json

### ISSUE THREAD

**Issue by Kukuruts** [inuyaksa/jquery.nicescroll#617]
There is a bug in your bower.json:

```
"main": [
        "./jquery.nicescroll.js",
        "./zoomico.png"
    ],
```

should be

```
"main": [
        "./jquery.nicescroll.min.js",
        "./zoomico.png"
    ],
```

**Comment by jacobdong** [comment]
+1

**Comment by bugdanov** [comment]
Hello,

I agree it's boring having to figure out what's happening and discovering this.

Often scripts are actually concatenated and uglified at packaging time.

Maybe it's better to include jquery.nicescroll.js in the bower package to allow transparency (and tweaking) during development stages of applications using jquery.nicescroll

Thanks !

**Comment by bugdanov** [comment]
as workaround you can add the git repository address in bower.json or install the package with ```bower install --save "https://github.com/inuyaksa/jquery.nicescroll.git#3.6.8"``` (with or without the version number)
