### ISSUE TITLE
drag delay

### ISSUE THREAD

**Issue by lovetoast** [inuyaksa/jquery.nicescroll#621]
is there anyway way to add a delay to the dragging? i'm finding on touchscreens it's too sensitive and doesnt allow the user to click buttons half the time becasue nicescroll thinks it's dragging

**Comment by inuyaksa** [comment]
last version add drag delay before scrolling

**Comment by lovetoast** [comment]
that's awesome, is there a setting for this?

**Comment by inuyaksa** [comment]
directionlockdeadzone, default value is set to 6 (px)
