### ISSUE TITLE
chrome body scroll not create rail

### ISSUE THREAD

**Issue by tienne** [inuyaksa/jquery.nicescroll#622]
hi
I am the developer of Korea
Not English a little

my web page body scroll use nicescroll
When connecting long not create bodys rail

nicescroll.js 837 line

```
if (!self.ispage || (!cap.cantouch && !cap.isieold && !cap.isie9mobile)) {
```

self.ispage = false
cap.cantouch = true
cap.isieold = false
cap.isie9mobile = false

reboot my computer 
cap.cantouch = false
just connecting long time
only chrome

why so happen?

**Comment by inuyaksa** [comment]
Please test last release
