### ISSUE TITLE
3.6.7 -3.6.8-fix, jQuery .html, .text problem

### ISSUE THREAD

**Issue by imbr** [inuyaksa/jquery.nicescroll#623]
Hello,
at the beginning I would like to **thank you** for such a great script!

**Link to visualize the problem:** [jsfiddle.net](https://jsfiddle.net/4qm353yq/3/) 

After calling the function that changes the contents of the block, NisceScroll **disappears for a split second**.
The same problem in pure javascript.

Tested on: Chrome, Mozilla, Opera.
Versions of the problem: >= 3.6.7

**In version 3.6.6 everything works properly!**

Thx

**Comment by Fabuqare** [comment]
I tried it, 
It works


Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: imbr <notifications@github.com> </div><div>Date:2016/08/13  2:08 AM  (GMT+02:00) </div><div>To: "inuyaksa/jquery.nicescroll" <jquery.nicescroll@noreply.github.com> </div><div>Cc:  </div><div>Subject: [inuyaksa/jquery.nicescroll] 3.6.7 -3.6.8-fix, jQuery .html, .text
  problem (#623) </div><div>
</div>Hello,
at the beginning I would like to thank you for such a great script!

Link to visualize the problem: jsfiddle.net

After calling the function that changes the contents of the block, NisceScroll disappears for a split second.
The same problem in pure javascript.

Tested on: Chrome, Mozilla, Opera.
Versions of the problem: >= 3.6.7

In version 3.6.6 everything works properly!

Thx

**Comment by imbr** [comment]
To see the problem, open the example on a **desktop device**.
RE: **Link to visualize the problem:** [jsfiddle.net ](https://jsfiddle.net/4qm353yq/3/)

**Comment by inuyaksa** [comment]
fixed flickering version >= 3.7.4
