### ISSUE TITLE
Unexpected behaviour when the html overflow set to hidden.

### ISSUE THREAD

**Issue by superbaj1986** [inuyaksa/jquery.nicescroll#624]
When we set the html and body overflow to hidden the scrollbar appears and it doesnt working, the expected behavior is, it should not show the scrollbar when we set to hidden, please refer the below style and html markup.

 html, body {
        height: 100%;
        margin: 0px;
        padding: 0px;
        border: 0px;
        width: 100%;
        overflow: hidden;
        font-family: 'Trebuchet MS';
        position: relative;
    }

$("html").niceScroll();

![capture](https://cloud.githubusercontent.com/assets/15935144/17731702/1a7b2d5a-648c-11e6-9701-f3a3711b824b.PNG)

**Comment by nikon321** [comment]
I have the same problem -_-
