### ISSUE TITLE
nicescroll with ontraport

### ISSUE THREAD

**Issue by Sparkle002** [inuyaksa/jquery.nicescroll#627]
hi,
i am using ontraport smart form. when i integrate ontaport form in my webpage with  js: "//forms.ontraport.com/v2.4/include/formEditor/genjs-v3.php?html=false&amp;uid=p2c103849f6" type="text/javascript">,

 scroll stops working and showing me error:  jQuery(...).niceScroll is not a function.

**Comment by inuyaksa** [comment]
ontraport seems override window.$

**Comment by Sparkle002** [comment]
Thank you for your reply but I solved this already. :)
