### ISSUE TITLE
Modal Popup

### ISSUE THREAD

**Issue by markmcgookin** [inuyaksa/jquery.nicescroll#63]
I have managed to get the scrollbar to work in a user control/modal popup (asp modalpopupextender) on a page built from a master page.

However, I can only see the new scrollbar for a fraction of a second before the popup covers it.

The div it is in scrolls correctly, but there is no bar displayed. I tried using the cursor css to set the zindex, but that made no difference.

I think that the scrollbar is behind the modal popup.

**Comment by berruno** [comment]
Yep, that fixes it :+1:
