### ISSUE TITLE
Blink in version "nicescroll v.3.6.8"

### ISSUE THREAD

**Issue by bear-wolf** [inuyaksa/jquery.nicescroll#632]
When you create new scroll or move element, all visible nicescrolls blink in version "nicescroll v.3.6.8"

**Comment by hvsh** [comment]
+

**Comment by ido172** [comment]
+1

**Comment by blinkcat** [comment]
I have also encountered this problem

**Comment by karam89** [comment]
+1

**Comment by vanxant** [comment]
Quick fix:  
```
.nicescroll-rails-vr {
 	display: block!important;
 }
```
in your CSS

**Comment by pgs-pliulia** [comment]
+1

**Comment by nabil999** [comment]
+1

**Comment by randNaN** [comment]
+1

also I tried vanxant's fix and it works somewhat, but when you hide a div that has a nicescroll object, it doesn't get rid of the scrollbar immediately.  It takes about 2 seconds for the scrollbar to disappear.

**Comment by Troy-Yang** [comment]
@vanxant Nice trick!

**Comment by Troy-Yang** [comment]
Following @vanxant 
`.nicescroll-rails-vr {
    display: block!important;
 }
 
 .nicescroll-rails-hr{
	 display: block!important;
 }`

Note: Works fine but just in desktop browser

**Comment by luka-sakun** [comment]
+1

**Comment by inuyaksa** [comment]
Fixed on 3.7.4
