### ISSUE TITLE
Versions from "3.6.7" to "latest" brokes scroll on touch devices

### ISSUE THREAD

**Issue by xhoskin** [inuyaksa/jquery.nicescroll#634]
**Example URL:**
http://plnkr.co/edit/CLVwvbdGUWXKfKmkiJ70?p=preview (3.6.7 - first broken version)
http://plnkr.co/edit/aP4Y6k68EfL32MpLfhUU?p=preview (v3.6.8 - latest)

**Steps to reproduce the problem:**
1. open http://plnkr.co/edit/aP4Y6k68EfL32MpLfhUU?p=preview on touch device or in Chrome DevTools Mobile Emulator
2. do scroll in a blue-bordered div
or watch the screencast: https://yadi.sk/d/0fjpMm-fwG5HM 
(click on big image to play)

**What is the expected behavior?**
Scroll must work on touch devices, like it works in ver. 3.6.6
Watch demo with ver. 3.6.6: http://plnkr.co/edit/semNHgg4wctU7DrWhj4q?p=preview

**What went wrong?**
Scroll by touch gestures (swipe up/down) don't work.

**Tested in browser versions**
1. Desktop Chrome version:  53.0.2785.143 m (OS Windows 7)
2. Mobile Chrome version 51.0.2704 (OS Android 5 on LG H324 Phone)
3. Mobile Safari version 7.1 (OS iOS 7.1 on Iphone 4S)

**Comment by ariona** [comment]
try using 3.6.6 but can't get it to work on Android M default browser

**Comment by xhoskin** [comment]
@inuyaksa, can you confirm a bug?

**Comment by alexgsummer** [comment]
I can confirm this bug still exists in 3.6.8. Viewing the [NiceScroll example](http://nicescroll.areaaperta.com/demo.html) in Chrome on Android does not scroll on touch move.

**Comment by odeciojunior** [comment]
@inuyaksa , @xhoskin  I had the same problem, even trying with these parameters: 

{ cursorcolor: '#bbb', cursorwidth: '6px', cursorborder: 'none', touchbehavior: true, cursordragontouch: true, preventmultitouchscrolling: false }

**Comment by nelwa** [comment]
Any update on this, or is this project dead?

**Comment by inuyaksa** [comment]
#646
