### ISSUE TITLE
Nicescroll get hidden behind the IE11 Scrollbar in full window.

### ISSUE THREAD

**Issue by abhibagul** [inuyaksa/jquery.nicescroll#641]
This problem happens when ie is open in fullscreen mode. However for the reduced size window it works well. but for fullscreen it causes problem.

![ie problem](https://cloud.githubusercontent.com/assets/12196126/20958373/4ac2f910-bc7b-11e6-8468-5bbdad073cf3.png)

**Comment by inuyaksa** [comment]
Fixed on 3.7.4
