### ISSUE TITLE
Horizontal scroll doesn't work on mobile devices tested with chrome & firefox on Android

### ISSUE THREAD

**Issue by nelwa** [inuyaksa/jquery.nicescroll#646]
Hi, Horizontal scroll doesn't work on mobile devices.  Tested with chrome & firefox on Android.

Please help.

**Comment by Tolc** [comment]
I have the exact same problem...
Can confirm that this is not working on Safari iPad as well.

**Comment by bydbest** [comment]
same issue. luckily i have found this. what is other possible alternative of nicescroll. in mobile these scroll looks good without nicescroll but in desktop it looks ugly so need some solution for bootstrap

**Comment by bravik** [comment]
Works on version 3.6.6 and broken on 3.6.7

**Comment by bravik** [comment]
So... I think it is about wrong touch detection. For v 3.6.8. To fix, you need to change on line 406 this:
```
//## Check WebKit-based desktop with touch support
    //## + Firefox 18 nightly build (desktop) false positive (or desktop with touch support)
    
    if (!cap.cantouch && (cap.hasw3ctouch||cap.hasmstouch)) {  // desktop device with multiple input
      this.istouchcapable = true;
    } else if (cap.cantouch && !cap.isios && !cap.isandroid && (cap.iswebkit || cap.ismozilla)) {
      this.istouchcapable = true;
//      cap.cantouch = false; // parse normal desktop events
    }
```

to this:
//## Check WebKit-based desktop with touch support
    //## + Firefox 18 nightly build (desktop) false positive (or desktop with touch support)
    
    if (!cap.cantouch && (cap.hasw3ctouch||cap.hasmstouch)) {  // desktop device with multiple input
      this.istouchcapable = true;
    } else if (cap.cantouch && (!cap.isios || !cap.isandroid) && (cap.iswebkit || cap.ismozilla)) {
      this.istouchcapable = true;
//      cap.cantouch = false; // parse normal desktop events
    }
```

**Comment by inuyaksa** [comment]
Problem identified, new passive mode on addEventListener and required preventDefault.
I'm working for fix

**Comment by DanielRuf** [comment]
I think there is some regression. It stopped working again or it's very laggy.
