### ISSUE TITLE
Native scroll not prevented well - background scroll happening

### ISSUE THREAD

**Issue by banago** [inuyaksa/jquery.nicescroll#648]
Hey @inuyaksa, thanks for building this great jQuery plugin. 

I ran into an issue lately. A background scroll still happens when you scroll a nice-scroll div. Please view the video below for an example: http://d.pr/v/E3vd/V5bgUO29 Also, here goes the URL where the issue is happening: http://staging.thespaces.com/

Is this a nicescroll issue?

**Comment by banago** [comment]
@inuyaksa the issue does not happen when I use the dev version (not minified). It seems it's fixed during your updates or by a pull request. Do you think you can bump the version and minify it so I can use the official version?

**Comment by inuyaksa** [comment]
Please check current version.
