### ISSUE TITLE
niceScroll does not work on mobile

### ISSUE THREAD

**Issue by geekasso** [inuyaksa/jquery.nicescroll#657]
It appears that touch mode does not work. I have discovered it in my implementation, but when I try it on the demo page (https://areaaperta.com/nicescroll/demo.html) I have the same outcome. I can scroll with mouse, but once I set to mobile mode or load it on the mobile, I am unable to scroll. The only way it scrolls on the mobile is if I remove overflow hidden, but then there are 2 scroll bars.

**Comment by geekasso** [comment]
Update: clicking the scrollbar to go up or down works, just cannot drag

**Comment by geekasso** [comment]
This is definitely an issue with this specific plugin and/or version. Since development has not been updated in quite some time, I ended up removing niceScroll implementation and went with .mCustomScrollbar (http://manos.malihu.gr/jquery-custom-content-scroller/) instead. Hopefully this alternative will work for others looking at this thread as well.

**Comment by DanielRuf** [comment]
I also have this issue. It stops working after a while.
