### ISSUE TITLE
something wrong with code

### ISSUE THREAD

**Issue by blackwhiteeagle** [inuyaksa/jquery.nicescroll#658]
var _touchaction = (cap.isie10) ? '-ms-touch-action' : 'touch-action';
if (cap.hasmstouch) self.css((self.ispage) ? $("html") : self.win, {
_touchaction: 'none'
});

you mean to set {'-ms-touch-action': 'none'} or {''touch-action': 'none'},
actually, {'_touchaction': 'none'}

**Comment by inuyaksa** [comment]
Thanks, it's a typos :D

**Comment by inuyaksa** [comment]
Thanks, I'm rewriting this part.
