### ISSUE TITLE
3.7.0 not published on npm

### ISSUE THREAD

**Issue by Kovensky** [inuyaksa/jquery.nicescroll#663]
As goes the title.

```
$ npm info jquery.nicescroll versions dist-tags
versions = [ '3.6.8' ]
dist-tags = { latest: '3.6.8' }
```

**Comment by Kovensky** [comment]
Wrong package name 🤦‍♂️

**Comment by inuyaksa** [comment]
Hello, name jquery.nicescroll is correct, there is a dispute with an user on npm who published old version.
So I've published as nicescroll
