### ISSUE TITLE
NiceScroll Not Working On firefox 49 

### ISSUE THREAD

**Issue by aixiaoxianggithub** [inuyaksa/jquery.nicescroll#665]
NiceScroll Not Working On firefox 49

**Comment by inuyaksa** [comment]
hi, there is some errors in console? (F12)

**Comment by SmallBoys** [comment]
no，I has an another erro on firefox 53.0(32)。when the div change from “block” to "none",and change back to "block"，the div’s nicescroll is disappeared.

**Comment by inuyaksa** [comment]
Do you have test lastest version (3.7.5) ?
