### ISSUE TITLE
mousewheel not working in safari & click event trigger twice in mobile

### ISSUE THREAD

**Issue by sayestec** [inuyaksa/jquery.nicescroll#669]
1. nicescroll version 3.7 having problem with mosewheel in safari 5.1.7(win)
2. I have a sidebar menu and there is having child collapse menu. when click to open collapse menu it hit twice within 0.4s. so my slideToggle() not working properly. it opens up and immediately closed. It happen only in mobile. desktop and laptop has no issue.

**Comment by inuyaksa** [comment]
Hi, do you have a link to test?
For mobile issue do you use iphone?

**Comment by sayestec** [comment]
for safari mousewheel issue plz check https://www.dropbox.com/s/tj8394ms2jmx9al/test.zip?dl=0

and mobile click issue - I use android phone

**Comment by inuyaksa** [comment]
Thanks I'm investigated

**Comment by inuyaksa** [comment]
Your issue is resolve on 3.7.2 (on developing)
Download this version to test on your site.
This is a pretty stable version, I'll release soon.
[jquery.nicescroll.js.zip](https://github.com/inuyaksa/jquery.nicescroll/files/1070632/jquery.nicescroll.js.zip)

**Comment by sayestec** [comment]
thanks :)

**Comment by rajakhoury** [comment]
I'm having the same issue. Nicescroll is initiated on the sidebar but when I attach an on click event on the links the event fire twice, I tried the 3.7.2 above and didn't solve the issue . Any idea ? It only firetwice when testing on mobile / touch devices.

// nice scroll

	$menuWrapper.niceScroll( {
		emulatetouch: !!$.Display.isTouch()  ,
		 //emulatetouch: false  ,
		cursorcolor: "#e7e7e7" ,
		cursorwidth:'6px',
		cursorborderradius: '3px',
		cursoropacitymin: 0,
		cursoropacitymax: 0.45,
		autohidemode: true,
		scrollspeed: 50,
		mousescrollstep: 35,
		zindex: "auto",
		hwacceleration: true,
		bouncescroll: true,
		cursordragontouch: true

	});

// On click event

	$menuItem.on('click', function(e) {
		e.preventDefault();
		e.stopImmediatePropagation();
		console.log('clicked')
		
		var link            =  $(this);
		var hasChildren     =  link.hasClass('has_children');

		
		if ( hasChildren ) {
		
			link.toggleClass('active');
			link.next('ul.level__2').slideToggle( 350 ) ;

		}

	});

// markup

	<nav id="sidebar">
		<div class="menu_wrapper">
			<div class="menu">
				<ul class="level__1">
					<li><a> ... </a></li>
				</ul>
			</div>
		</div>
	</nav>

If I set `emulatetouch : true` I get this error : 
`edd1172…-1497413756:2939 Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLDocument.self.ontouchmove (edd1172…-1497413756:2939)`

in 
` if (e.targetTouches.length>1) console.log(e.pointerType);`

**Comment by sayestec** [comment]
var previousClickTime = new Date();

	$menuItem.on('click', function(e)
	{
		var currentClickTime = new Date();
		var diffTime = (currentClickTime.getTime() - previousClickTime.getTime()) / 1000;

		if(diffTime > 0.5)
		{
                     // Your event code here
			previousClickTime = currentClickTime;
		}
	});

**Comment by rajakhoury** [comment]
Not sure how this solves the issue

**Comment by inuyaksa** [comment]
Please try this version:
[Uploading jquery.nicescroll.js.372k.zip…]()

**Comment by rajakhoury** [comment]
@inuyaksa Thanks but I tried the version 3.7.2 linked above when I wrote this issue.

**Comment by inuyaksa** [comment]
@rajakhoury that is a new version

**Comment by rajakhoury** [comment]
@inuyaksa Thanks for the time but still no luck. I have attached a gif showing the behavior, first time click fire once , all other twice. trying to figure out this since yesterday :/ about the error when `emulatetouch : true` still shows up

![2017-06-14_15-59-18](https://user-images.githubusercontent.com/4506434/27154404-8e01eb58-511a-11e7-9589-28c8e9b5bba7.gif)

**Comment by inuyaksa** [comment]
Please check this: 
- do you have clear the cache?
- tested on mobile? (it could be issues on chrome emulation)

**Comment by rajakhoury** [comment]
Yes, I clear the app and browser cache before every try. I tested this on my android phone HTC Desire Android 4.4.2 ( Chrome ) and it is the same problem.
- If I remove nicescroll everything works fine, tested also with other scroll bar plugins without problem.
- There are not other onclick events attached to the links
- if I add touchstart instead click `$menuItem.on('touchstart'`.. then the menu behaves as expected but I can't do that because on mobile when the user is dragging down the list it will toggle the links

**Comment by rajakhoury** [comment]
I can confirm it is working fine on the default android browser maybe it is chrome issue

**Comment by inuyaksa** [comment]
Thanks for testing, I'm investigating on chrome.

**Comment by inuyaksa** [comment]
@rajakhoury please try this new version:
[jquery.nicescroll.js.372q.zip](https://github.com/inuyaksa/jquery.nicescroll/files/1082449/jquery.nicescroll.js.372q.zip)

**Comment by rajakhoury** [comment]
@inuyaksa Perfecto!!! :))))
