### ISSUE TITLE
The scrollbar doesn't work only if resize the browser window

### ISSUE THREAD

**Issue by themevan** [inuyaksa/jquery.nicescroll#670]
Hi

I'm sorry that I haven't searched related issue yet, so I have to ask here. 

This is my customer's website http://jsbcom.ovh/lavoiedes5points/ when you click these buttons, https://www.dropbox.com/s/r7q0ppboebdgfsr/Screenshot%202017-06-14%2001.06.27.png?dl=0 it will display a popup, there's no scrollbar, but when I resized the browser window, the scrollbar was working. 

Could you give me any suggestions to fix this issue?

Thanks

**Comment by inuyaksa** [comment]
You have to create nicescroll when box is open and remove it before close the box.

I have tryed this command with box open, and It works (it needs some adjust on title and content):
$(".fp-button-popup-content").niceScroll();

I hope to be helpfull
