### ISSUE TITLE
use nicescroll in IE8

### ISSUE THREAD

**Issue by webLeeSun** [inuyaksa/jquery.nicescroll#672]
Please excuse me. 
I have a question when use dist/jquery.nicescroll.min.js in IE8. 
It says "SCRIPT1002：语法错误   jquery.nicescroll.min.js (232,13)"
But when I use dist/jquery.nicescroll.js in  the same code.Everything is ok.
Thanks for your help!

**Comment by inuyaksa** [comment]
Thanks I'm investigating

**Comment by inuyaksa** [comment]
You can use developer version:
https://github.com/inuyaksa/jquery.nicescroll/tree/dev-dojo

**Comment by webLeeSun** [comment]
I got it.Thanks a lot!
