### ISSUE TITLE
Vertical Scroll on Parent div, and horizontal to its child blocks

### ISSUE THREAD

**Issue by meesha93** [inuyaksa/jquery.nicescroll#673]
I have implemented nice-scroll to the parent-div of a list, it works fine until I add horizontal scroll to its list-items. It gets sluggish and unresponsive.

**Comment by inuyaksa** [comment]
Please test developing branch:
https://github.com/inuyaksa/jquery.nicescroll/tree/dev-dojo

**Comment by meesha93** [comment]
Thanks for the reference. But it stopped working altogether.  Am trying it with angular2.* 

Does it support this version of angular?

**Comment by inuyaksa** [comment]
I don't contribute directly to angular plugin, please write to mantainer.
