### ISSUE TITLE
no drag and scroll

### ISSUE THREAD

**Issue by JanJordan** [inuyaksa/jquery.nicescroll#676]
i have the latest version and styling and behaviour in general are working great.

The only Problem is that the scrollbar can not be dragged or clicked to scroll the viewport. Scrolling with the mousewheel ist working fine, only the "normal" behaviour of the bar is not.
Looks a bit as if the mousedown or click events do not get through to the scrollbar object or if they are not handled there.

best
jan

**Comment by inuyaksa** [comment]
Please paste here nicescroll parameters.

**Comment by JanJordan** [comment]
here we go. 

`
           
              $(document).ready(function() {
              
                var nice = false;
                  $(function() {  
                      nice = $("html").niceScroll({
                        cursorcolor: "#00a351", // change cursor color in hex
                        cursoropacitymin: 0, // change opacity when cursor is inactive (scrollabar "hidden" state), range from 1 to 0
                        cursoropacitymax: 1, // change opacity when cursor is active (scrollabar "visible" state), range from 1 to 0
                        cursorwidth: "8px", // cursor width in pixel (you can also write "5px")
                        cursorborder: "0px solid #fff", // css definition for cursor border
                        cursorborderradius: "0px",
                        autohidemode: false,
                        railalign: "right",
                        railpadding: { top: 0, right: 0, left: 0, bottom: 0 },
                        emulatetouch: false,
                        sensitiverail: true,
                        background: "#ccc",
                        zindex:99999,
                        hidecursordelay: 4000,
                        boxzoom: false,
                        grabcursorenabled:false
                    });
                    console.log(nice);
                  });
                
              });

          `


But i have the same behaviour without any spcial params, like this:

`
 nice = $("html").niceScroll({});
`

**Comment by inuyaksa** [comment]
Any browsers?
Can you try with $("body") element?

**Comment by JanJordan** [comment]
really strange. It works under IE11, but not under Chrome or FF..
$("body") makes no difference
i am on a win8.1 System with touchscreen, will try other os/screens next

**Comment by JanJordan** [comment]
interesting: (pc under win10) with chrome and edge it is working as expected.
BUT the screen on this system has noch touch device.

On the other system (notebook lenovo yoga) we have a touch screen and there it is not working (except under ie11).

**Comment by inuyaksa** [comment]
It seems a issue on touch enable desktop.

Try setting cursordragontouch to true it could fix the problem.

**Comment by JanJordan** [comment]
yes, it is only on touch devices.
cursordragontouch : true fixes this:
(tested on win8.1 touch) current FF, IE11, and (partial) current Chrome

under chrome it works, but the behaviour ist not the same as in other browsers: scrolling of the viewport does not take place during mousedown + move, but on mouseup (so you push mousedown, move cursor around without visual feedback and on mouseup the scrolling takes place)

this is ok for me for now - thank you very much for your help and the great work!
if i should test an optimized chrome Version on my touch device just let me know.
best regards
jan

**Comment by inuyaksa** [comment]
Please test dev version https://github.com/inuyaksa/jquery.nicescroll/tree/dev-dojo

**Comment by JanJordan** [comment]
grreat - now it works with chrome on touch devices too.
cursordragontouch : true is needed (on my device) to make the bar clickable, otherwise one can only use dragndrop to move the viewport

thanks alot! 👍

**Comment by madprops** [comment]
I'm having the same problem but I kinda found a fix, or at least a clue that might help to fix a possible bug. 

```
autohidemode: false,
cursorcolor: color,
cursorborder: "0px solid white",
enablekeyboard: false
```

Mouse click drag doesn't work, but when I remove the the scrollbar with .getNiceScroll().remove() and then start nicescroll again (on the same element) --- it works!

By the way I don't have a touch enabled monitor.

**Comment by madprops** [comment]
Seems it was a z-index problem.
