### ISSUE TITLE
scroll is not working on edge and firefox browsers in touchscreen laptops

### ISSUE THREAD

**Issue by pandu5164** [inuyaksa/jquery.nicescroll#677]
Hi, I am using touch screen laptop. I added this plug-in for testing on firefox and edge browsers. I'm unable to scroll content by touching screen. Please let me know how to fix them. Is there any patch/update available?
Note:- 2finger gesture scroll is working is working. but single finger is not working. Where as it works fine in  chrome browser.

Thankyou.

**Comment by inuyaksa** [comment]
Please let me know if my page works:
https://nicescroll.areaaperta.com/demo/

**Comment by pandu5164** [comment]
Hi,

Sorry for the delayed response.
Your demo URL is not working in the mentioned browsers.
Kindly let me know the fix/update

Regards,
Pavan Z.


On 8 Jul 2017 12:58 am, "Inuyaksa" <notifications@github.com> wrote:

Please let me know if my page works:
https://nicescroll.areaaperta.com/demo/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/inuyaksa/jquery.nicescroll/issues/677#issuecomment-313772176>,
or mute the thread

**Comment by inuyaksa** [comment]
Please I need more infos about your device, then make a screenshot of this page:
https://nicescroll.areaaperta.com/dojo2/browser.html

**Comment by pandu5164** [comment]
Hi,
About my devices:-
1. Microsoft surface pro4 (4GBRAM/128GBSSD)
2. Lenovo Yoga 510 - Touchscreen laptop (8GB RAM/Corei5/500GBStorage)
These are the 2 devices i am using and configurations of those devices.

I attached screen shots of 2 browsers with comments as file name of that
picture.

In edge browser that particular URL (
https://nicescroll.areaaperta.com/dojo2/browser.html ) is working I'm able
to scroll, but *in Firefox still scroll not working*. please observe the
screenshots attached.

Kindly look into it and let me know the fix/workaround if available.

Regards,
Pavan Z.

**Comment by inuyaksa** [comment]
Hi, you miss image

**Comment by pandu5164** [comment]
<img width="960" alt="mozilla firefox - scroll not working - instead it is selecting on scroll - issue" src="https://user-images.githubusercontent.com/12708980/28114506-bdadd37a-671e-11e7-953e-87feca2007b7.PNG">
<img width="960" alt="scroll working in this particular page on edge browser" src="https://user-images.githubusercontent.com/12708980/28114505-bdabdd5e-671e-11e7-9ee0-b1e950af9a88.PNG">


Please find the attached images and comments for it i mentioned yesterday.

**Comment by inuyaksa** [comment]
It seems Firefox 47 do not implement touch support for javascript, as stated here:
https://developer.mozilla.org/it/docs/Web/API/TouchEvent

You can resolve add nicescroll parameter emulatetouch and set to true.

Screenshots do you posted as about Lenovo or Surface?

Yesterday made a little fix for Surface, please test demo page:
https://nicescroll.areaaperta.com/demo/

**Comment by pandu5164** [comment]
Hi,
Screenshots I posted is of Lenovo touchscreen laptop.

Regards,
Pavan Z.

**Comment by inuyaksa** [comment]
Only updated Firefox works or you need set emulatetouch to true
Do you have checked with parameter set to true?

**Comment by pandu5164** [comment]
Hi
Can you zip and send me the latest updated version of nicescroll plugin. I will keep it in my application and check whether my problem is resolved or not in firefox and edge browsers.

**Comment by inuyaksa** [comment]
I hope to release soon the stable 3.7.5 version.
In the meanwhile you can user dojo version https://github.com/inuyaksa/jquery.nicescroll/tree/dev-dojo

**Comment by pandu5164** [comment]
Hi,I am getting the following error after updating the plugin. Please let me know why it is happening.
![capture7](https://user-images.githubusercontent.com/12708980/28276335-402b9814-6b34-11e7-84f9-253c6f952b3a.PNG)
![capture8](https://user-images.githubusercontent.com/12708980/28276334-40298fb0-6b34-11e7-9678-c8a4432c2616.PNG)

**Comment by pandu5164** [comment]
Hi,

After updating the plugin to 3.7.5 i am getting error when we try to
call *remove(
)* function to niceScrollObj. This is happening most of the times in
application & I already mentioned the comment in github but i didn't get
any response till now so i am mailing you. please respond to this. please
let me know if there is any workaround/alternative available for remove( )
in nicescroll.

Note:- attached images in this mail.


Regards,
Pavan Z.

**Comment by inuyaksa** [comment]
Hi, do you call remove or you delete a DOM element?

**Comment by pandu5164** [comment]
Hi,
Actually i am using modal window pop-up which has scrollable content in it. while closing the pop-up i am destroying the modal(completely removing from DOM) at that time i am getting this error..Earlier plugin 3.6.8V doesn't used throw this error.

**Comment by pandu5164** [comment]
Hi,
Actually i am using modal window pop-up which has scrollable contents in
it. while closing the pop-up i am destroying(calling angular - $destroy)
the modal(completely removing from DOM) at that time i am getting this
error..Earlier plugin 3.6.8V doesn't used throw this error.

Regards,
Pavan Z

**Comment by inuyaksa** [comment]
Thanks for the infos, I'm investigating

**Comment by inuyaksa** [comment]
Sorry, I can't reproduce issue.
Please check the code on this page and let me know how different is your code (I know you use angular)
https://nicescroll.areaaperta.com/dojo2/modal.html

**Comment by inuyaksa** [comment]
@pandu5164  please continue on new issue #683
