### ISSUE TITLE
scroll in a scroll container

### ISSUE THREAD

**Issue by suifengshiqu** [inuyaksa/jquery.nicescroll#678]
how to using scroll in another scroll container,when parent scroll show the children's scroll is dislocation

**Comment by inuyaksa** [comment]
Better use wrapped div container.
Get code from last example of this page:
https://nicescroll.areaaperta.com/demo/

**Comment by suifengshiqu** [comment]
sorry,it's not clear,so i write an example to show my operation. i have run the resize method but position of the children's scroll haven't change , so the scrollbar position is error.
[http://runjs.cn/code/kqmxcfye](url)

**Comment by inuyaksa** [comment]
Link doesn't works.

**Comment by suifengshiqu** [comment]
sorry, the url set error, i have updated.[http://runjs.cn/code/kqmxcfye](http://runjs.cn/code/kqmxcfye)

**Comment by inuyaksa** [comment]
Please use last version 3.7.4

https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.4/jquery.nicescroll.min.js

**Comment by wangganlin** [comment]
I have the same problem!    Have you solved it?

**Comment by suifengshiqu** [comment]
@wangganlin 没有啊，3.7.5也不行啊

**Comment by suifengshiqu** [comment]
@inuyaksa when i change the script to 3.7.5,the probelem is still [http://runjs.cn/code/kqmxcfye](http://runjs.cn/code/kqmxcfye)

**Comment by suifengshiqu** [comment]
@inuyaksa im sorry,it's my mistake,i have resolve it when i have studied with the  doc.
@wangganlin 看这里[http://runjs.cn/code/kqmxcfye](http://runjs.cn/code/kqmxcfye)
