### ISSUE TITLE
Calling .remove() throws an error after update to v. 3.7.4

### ISSUE THREAD

**Issue by sebhewelt** [inuyaksa/jquery.nicescroll#681]
In my react app I call .remove() method on body:

```
 componentWillUnmount() {
   
 $("body").getNiceScroll().remove();

  }
```

It throws an error:

> Uncaught ReferenceError: del is not defined
>     at NiceScrollClass.undelegate

Is remove() deprecated? How to remove the scrollbar completely other way?

cheers.

**Comment by inuyaksa** [comment]
Fix soon
