### ISSUE TITLE
Is nicescrol compatible with Materializecss?

### ISSUE THREAD

**Issue by gusbemacbe** [inuyaksa/jquery.nicescroll#682]
Hello,

I use Materialize framework and applied nicescroll to tag html, but the scrollbar doesn't get effect. 

I think that nicescroll and Materialize are incompatible.

**Comment by inuyaksa** [comment]
Please, try adding nicescroll to the body element.

**Comment by gusbemacbe** [comment]
I added `body` and it didn't get effect either.

**Comment by inuyaksa** [comment]
Any error in console?

**Comment by gusbemacbe** [comment]
No, as I checked the console. There is no error. 

```
<script type="text/javascript">
$(function() {  
    $("html").niceScroll();
});
</script>
```

Is this code correct?

**Comment by inuyaksa** [comment]
I'm investigating, materailizecss is new for me

**Comment by gusbemacbe** [comment]
Read, @inuyaksa, read our discussion: https://github.com/Dogfalo/materialize/issues/4984, applying to HTML worked, but to side-navbar, it not worked.

**Comment by inuyaksa** [comment]
Reply https://github.com/Dogfalo/materialize/issues/4984#issuecomment-316623911

**Comment by gusbemacbe** [comment]
Ah, somebody suggest me to move sidenav outside navbar and it worked, but the nicescroll is still inside the navbar:

https://codepen.io/gusbemacbe/pen/rwXawx

**Comment by inuyaksa** [comment]
It seems all works, but your navbar has no others elements to display so scrollbar has hidden.
Try to set height: 200px to #slide-out
