### ISSUE TITLE
nicescroll width not changed inside textarea

### ISSUE THREAD

**Issue by HaliAlduhoky** [inuyaksa/jquery.nicescroll#684]
Hello bro,
     I tried to use this plug-in with $("textarea"), but the problem is the width not changing !!! it's more than 7px i use this property to change it width inside textarea ( cursorwidth: "2px" ) not working!

this problem just with textarea !
Working well for other elements.
hope to resolve this problem or assets me if there have another way to change it width inside textarea. 

Thanks.
Hali

**Comment by inuyaksa** [comment]
Hi, which browsers have this issue?

**Comment by inuyaksa** [comment]
Testing with textarea no issue found.
Please check this: https://codepen.io/anon/pen/YQmXbz

**Comment by HaliAlduhoky** [comment]
I talking with you right now in work, really no issue found in codePen.
i will check the same PEN you gives me in my browser.
i do not know what's the problem, but i will try to resolve it.

please do not remove that PEN.

Thank you for your replay.
Hali

**Comment by HaliAlduhoky** [comment]
My issue resolved bro.
There have another issue when using niceScroll for textArea, that's when you hold on Enter quickly the scroll going outside textarea for few seconds. try this in your PEN you gives me and hold on Entry for many times quickly and you will see the scroll going outside the textarea and going back to it place again.
 
Please make something for this issue.

**Comment by inuyaksa** [comment]
I see the issue, I'll fix soon.

**Comment by HaliAlduhoky** [comment]
Ok, All will be happy to fix that.

Thanks a lot.
