### ISSUE TITLE
Possible bug in NiceScroll v3.7.4+

### ISSUE THREAD

**Issue by ilicfilip** [inuyaksa/jquery.nicescroll#686]
Hello,

recently we've updated from NiceScroll v3.5 to v3.7.4 and we've noticed a problem on pages which use infinite scroll.

Once new content is loaded on such pages resize event is triggered, but from some reason NiceScroll script doesn't take that in account and user can't scroll to see new content.

This used to work without a problem and downgrading to v3.7.3 solves the issue. Also, we've tested this with latest NiceScroll version (currently 3.7.6) and it also doesn't work.

Is this a bug or maybe something was changed on purpose in your script and we need to adjust our script as well?

ThemeFusion Team

P.S.
Just adding our lead dev @maximus80

**Comment by inuyaksa** [comment]
Hi @ilicfilip and @maximus80,
since 3.7.4 resize event has effect only when size changed on page. (to prevent scrollbar flickering)
You can resolve your problem using:
`$("#div").getNiceScroll().resize()`

**Comment by ilicfilip** [comment]
Thank you! :)

**Comment by rejowanahmed** [comment]
The problem still remains
