### ISSUE TITLE
autohide: 'hidden' not working

### ISSUE THREAD

**Issue by DanielRuf** [inuyaksa/jquery.nicescroll#688]
Calling `$('.some-wrapper').niceScroll().hide()` and `$('.some-wrapper').niceScroll({autohidemode:'hidden'});` do not work for me. The `hide()` call does not hide the element. The other values for `autohidemode` work without any issues.

Not sure if this is general or just in specific use cases.

**Comment by inuyaksa** [comment]
Hi, I can't reproduce, do you use last version 3.7.6?

Please post the result of this page:
https://nicescroll.areaaperta.com/dojo2/browser.html

**Comment by DanielRuf** [comment]
> Hi, I can't reproduce, do you use last version 3.7.6?

I see that it works when the DOM is fully available but I  still trigger `hide()` in document.ready and it does not work. But it works when I executy the code in the browser console. Might this because of some other triggered events after this? The other autohide options work.

I could solve it using a workaround (setting heights to 0 and so on. Just as a sidenote: values ar enot consistent, some use px some not).

**Comment by inuyaksa** [comment]
Which browser do you use?
Please test this example:
https://jsfiddle.net/udcam2L1/

**Comment by DanielRuf** [comment]
I've used Chrome 59 on Windows 10 (at home, I am currently at work).

**Comment by inuyaksa** [comment]
My example works on your config?

**Comment by DanielRuf** [comment]
Theexample works, yes.
