### ISSUE TITLE
delegated events are not cleaned up propperly

### ISSUE THREAD

**Issue by volkerrichert** [inuyaksa/jquery.nicescroll#762]
If you have multiple nicescroll on a page and "remove()" one of them the delegated events are not clean up an will result in a a lot of

> jquery.nicescroll.js:1259 Uncaught TypeError: Cannot read property 'rail' of null
>    at HTMLHtmlElement.self.ontouchmove (jquery.nicescroll.js:1259)
>    at HTMLDocument.f (jquery.nicescroll.js:2492)

when you move your mouse (touch emulation enabled).

I try to find out what happend:
- All niceScroll will register a delegate on "pointermove" `self.delegate(_doc, "pointermove", self.ontouchmove)` line 1653 (Chrome on Win10 with touch screen)
- but only the first niceScroll will register this event into his event list
- the 2ff will ship it, beause "pointermove" it's already in delegatevents
- if a niceScroll (not the first one) is removed it will not find event "pointermove" and the delegation will try to run ontouchmove on all(!) niceScroll. 
- inside the deleted niceScroll self if null, because it's remove `self = null; line 2674`

**Comment by davidsturgeon** [comment]
I fixed this by changing the .delegate to a .bind
I'm not sure what delegate is even doing.

**Comment by sKopheK** [comment]
Hi, @davidsturgeon have you merged your changes anywhere? We are facing the same issue and @inuyaksa  does not seem to be following issues in this repository.
