### ISSUE TITLE
Scrollbar not update after change content dynamic

### ISSUE THREAD

**Issue by blackfatpig** [inuyaksa/jquery.nicescroll#8]
If I try to change inside content of the DIV dynamic. After that, I cannot scroll or do something any more with th scrollbar.  Is there nay way to update scrollbar like the first time?

Thanks a lot.

**Comment by bear-wolf** [comment]
I have current version 3.5.0, this problem is actual for me.
I want do update:
`$('#list-table_wrapper').getNiceScroll().resize()`

This is not working
