### ISSUE TITLE
how to animate to scrollTop = 0

### ISSUE THREAD

**Issue by geertbrit** [inuyaksa/jquery.nicescroll#98]
Consider a search page with paging (through ajax) . I want to animate the searchresults (with nicescroll) but can't figure out a way to do it. 

I've found setScrollTop in the code and this (setScrollTop(0)) results in the correct position. I however want to animate to that position. Anyway to do that?

**Comment by euginepj** [comment]
ya. it is not working for me either. 

this is my code. 
`$('body').animate({scrollTop: 485}, 2000);`
The animation is stopped each time when covering each pixel. 

This code is working for me: (without any animation)
```
document.body.scrollTop = top; // For Safari
document.documentElement.scrollTop = top; // For Chrome, Firefox, IE and Opera
```
